### ISSUE TITLE
spyder autocomplete not finishing dataframe column names 

### ISSUE THREAD

**Issue by Travis-Barton** [spyder-ide/spyder#11881]
Hey all,

Using Spyder 4.1.1 and python 3.7 here and the auto complete cannot finish column names in pandas dataframes.

I have a data frame with the column 'waveform_id' and when I run the following:

    import pandas as pd
    data = pd.read_csv('my_data.csv')

and then try to use the autocomplete to finish:
    data['wav
it comes up with everything OTHER than the column name.

Any fixes?

**Comment by goanpeca** [comment]
Is this something that should be working at the moment @andfoy , @ccordoba12 ?

**Comment by ccordoba12** [comment]
> it comes up with everything OTHER than the column name.

What do you mean by this @Travis-Barton?

**Comment by goanpeca** [comment]
HE means that the completions options (the fallback ones) appear and in those there is no sign of the  dataframe columns

**Comment by Travis-Barton** [comment]
Hey @ccordoba12, @goanpeca has it exactly right. It gives me loads of things like 'Arithmetic error' but no column names of any kind. 
I'll try to be more concise in the future.

**Comment by ccordoba12** [comment]
Works for me:

![Selección_018](https://user-images.githubusercontent.com/365293/77458331-04d44e80-6dcc-11ea-9b5b-611f8c2d72c0.png)

> It gives me loads of things like 'Arithmetic error' but no column names of any kind.

If still get that, then you're not using 4.1.1. I spent a lot of time fixing it.

My recommendation is to create a new conda env and install 4.1.1 there. In any case, there's nothing for us to do here, so I'm closing this one.

**Comment by Travis-Barton** [comment]
> Works for me:
> 
> ![Selección_018](https://user-images.githubusercontent.com/365293/77458331-04d44e80-6dcc-11ea-9b5b-611f8c2d72c0.png)
> 
> > It gives me loads of things like 'Arithmetic error' but no column names of any kind.
> 
> If you still get that, then you're not using 4.1.1. I spent a lot of time fixing it.
> 
> My recommendation is to create a new conda env and install 4.1.1 there. In any case, there's nothing for us to do here, so I'm closing this one.

That works for me too if I explicitly have the word 'bar' in the script somewhere. But that won't work if you load a csv and just ask it to complete the column name. I am running 4.1.1.

**Comment by ccordoba12** [comment]
> That works for me too if I explicitly have the word 'bar' in the script somewhere.

Sorry, I totally missed that! Then, this is a missing functionality in [Jedi](https://github.com/davidhalter/jedi), the code completion library we depend on, so (still) there's nothing we can do about it, sorry.

However, Kite can give completions for dict keys, so maybe it can complete Pandas column names too.

**Comment by Travis-Barton** [comment]
> However, Kite can give completions for dict keys, so maybe it can complete Pandas column names too.

Gotcha! Thanks!

Is that something I can do from spyder's settings? Or is that something I can possibly do from kite?

**Comment by ccordoba12** [comment]
It should work by default once you've installed Kite. To install Kite from Spyder, you can go to the `Tools` menu and select the entry for it.

**Comment by Travis-Barton** [comment]
I have it installed and running, it must not be able to /: unless I have some settings configured weird.

![Screen Shot 2020-03-24 at 11 44 22 AM](https://user-images.githubusercontent.com/39603097/77464692-cedf9c00-6dc4-11ea-8d5d-8f89cb400181.png)

**Comment by ccordoba12** [comment]
You should see a `Kite: ready` message in the status bar, if everything is working fine.

**Comment by Travis-Barton** [comment]
I have that, but still no luck, oh well!

**Comment by ccordoba12** [comment]
@metalogical, does Kite support completion of Pandas column names? Or do you plan to add it in the future?

**Comment by metalogical** [comment]
Kite currently handles dicts, but not dataframes. Supporting pandas better is in our backlog, but unfortunately is not currently very high priority, so no word on when it'll happen. I will let our PM know that there is some external demand for this feature.

**Comment by ccordoba12** [comment]
Thanks for the explanation @metalogical!
