### ISSUE TITLE
Figure window doesn't show up with spyder icon on task bar (Windows)

### ISSUE THREAD

**Issue by MaartenBransen** [spyder-ide/spyder#12301]
### What steps will reproduce the problem?

When opening e.g. matplotlib figures in a seperate window, the icon for the figure windows on the taskbar under Windows 10 have the default "missing icon" icon, instead of the the Spyder icon. The Spyder IDE itself does have the correct icon.

Issue started after upgrading to 4.1.2. Have since done a completely clean install of anaconda+spyder (for unrelated reasons) and to my surprise the same issue popped up again.

## Versions

* Spyder version: 4.1.2 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.1 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by ccordoba12** [comment]
We really don't have control over the icon shown in Matplolib generated windows.

@dalthviz, what icon are you seeing for those windows?

**Comment by dalthviz** [comment]
Hi @MaartenBransen could you provide an screenshot or GIF to better understand what is happening in your case? Also, what back-end are you using? This is what I get if I use the `Automatic` backend option (the generated window has the matplotlib icon):

![image](https://user-images.githubusercontent.com/16781833/79139871-b12aa480-7d7c-11ea-9e36-352353664e01.png)

Maybe are you referring to some other kind of window?

Any new info in order to understand this is greatly appreciated :)

**Comment by MaartenBransen** [comment]
![spyder_icon_issue](https://user-images.githubusercontent.com/54527765/79195908-5f8f2200-7e2f-11ea-8ab6-361778ebd1f9.png)

Before I would see another spyder icon where the file-like symbol is now shown.. I think I may have also seen the Matplotlib icon as in the example of @dalthviz but I cannot remember if that was on this machine or another one, and/or which version or use case. I checked two other PCs with windows and previous spyder 4 versions, they both show the spyder icon for figure windows.

I am indeed using the Automatic backend (as selected in preferences - IPython console - graphics -graphics backend).

The reason I thought it might be a Spyder specific issue (rather than a Windows issue) was that this started specifically when I updated to 4.1.2. Initially did not think much of it, but was surprised to see it return immediately after a clean install of Anaconda + upgrading Spyder.

**Comment by ccordoba12** [comment]
@MaartenBransen, we don't have control over those icons, nor we did anything to change them in 4.1.2.

What's your Matplotlib version? This should be fixed in a recent enough version, if I'm not mistaken.

**Comment by dalthviz** [comment]
After testing a little bit more I was unable to reproduce this. Some of the scenarios tested were: running from file, running directly from the console, using `matplotlib` 3.1.1 and `matplotlib` 3.1.3. 

Always the taskbar icon has the `matplolib` icon.

@MaartenBransen maybe you can check if removing a file call `IconCache.db` from `C:\Users\your_user\AppData\Local` and doing a reboot (or restarting explorer.exe) can help.

**Comment by MaartenBransen** [comment]
> @MaartenBransen, we don't have control over those icons, nor we did anything to change them in 4.1.2.
That's fair enough, it is anyway not a major issue but I opened it because I assumed it was Spyder related, if it is not, I can look elsewhere.

> What's your Matplotlib version? This should be fixed in a recent enough version, if I'm not mistaken.
It was 3.1.3, I have now tried upgrading to 3.2.1 which did not solve the issue.



> After testing a little bit more I was unable to reproduce this. Some of the scenarios tested were: running from file, running directly from the console, using `matplotlib` 3.1.1 and `matplotlib` 3.1.3.
I tried running spyder from a desktop shortcut and from the console, but I didn't mention as it did not make a difference 

> Always the taskbar icon has the `matplolib` icon.
interesting, I have always had the spyder icon

> @MaartenBransen maybe you can check if removing a file call `IconCache.db` (hidden file) from `C:\Users\your_user\AppData\Local` and doing a reboot (or restarting `explorer.exe`) can help.
Tried, but it did not make a difference.

Thanks to both for the suggestions. I can try more things to troubleshoot, or if it is likely not spyder related this issue can be closed.

**Comment by ccordoba12** [comment]
> or if it is likely not spyder related this issue can be closed.

I'll close it for now, but please keep us posted here in case you find a fix.
