### ISSUE TITLE
Pytorch method 'detach' already has a docstring

### ISSUE THREAD

**Issue by alidiak** [spyder-ide/spyder#12701]
## Problem Description

Hello, whenever the pytorch/torch package is imported and I try to import again (say when I just run the whole script or another script that uses import torch) I get the error output: "method 'detach' already has a docstring". I'm not the only one experiencing this issue (see https://discuss.pytorch.org/t/method-detach-already-has-a-docstring/74676/12) and it seems to be a Spyder specific issue. 

### What steps reproduce the problem?

1. Import torch in Spyder
2. rerun import torch (rerun a script)

### What is the expected output? What do you see instead?

The script runs normally the first time, but upon rerunning, it errors on import.

### Paste Traceback/Error Below (if applicable)

```python-traceback


  File "/home/alex/Documents/QML_Research/Variational_Learning_Implementations/Python_Autoregressive/Test_E_loc", line 9, in <module>
    import torch

  File "/home/alex/anaconda3/envs/Pytorch/lib/python3.6/site-packages/torch/__init__.py", line 188, in <module>
    from .tensor import Tensor

  File "/home/alex/anaconda3/envs/Pytorch/lib/python3.6/site-packages/torch/tensor.py", line 41, in <module>
    class Tensor(torch._C._TensorBase):

  File "/home/alex/anaconda3/envs/Pytorch/lib/python3.6/site-packages/torch/tensor.py", line 282, in Tensor
    """)

RuntimeError: method 'detach' already has a docstring

```

## Versions

* Spyder version: 3.2.8
* Python version: 3.6 
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Ubuntu, 18.04

### Dependencies

```
```

Thanks for the help and hard work, Spyder is a great IDE

**Comment by AkmaralMoldagalieva** [comment]
The same problem.

**Comment by bcolsen** [comment]
I can run a script that contains only `import torch` multiple times without error. Is there anything else that might be needed to reproduce this?

Spyder 4.13 on ubuntu 16.04, pytorch version 1.4.0

@alidiak Your Spyder version is very old. Please update.

**Comment by AkmaralMoldagalieva** [comment]
Yes, You are right. Installing the newest version of Spyder worked for me.

**Comment by goanpeca** [comment]
Thanks for the report @alidiak and the input @bcolsen 

Glad you got it working now @AkmaralMoldagalieva !

Will close since this seems to be fixed in a recent version.

Cheers!

**Comment by ccordoba12** [comment]
Yeah, it was fixed a long time ago.

**Comment by alidiak** [comment]
Ok thank you. I did use 'conda update spyder' and retried before I submitted this report. It's strange that it wants to keep me on version 3.2.8, but if 4.0> are stable, I'll find another way to update. Thanks.

**Comment by goanpeca** [comment]
@alidiak you can try:

```
conda update anaconda
conda install spyder=4.1.3
```

**Comment by alidiak** [comment]
Thanks for the prompt response. When trying conda update anaconda and install spyder=4.1.3, I get the 'Found conflicts! Looking for incompatible packages.' error (see https://github.com/spyder-ide/spyder/issues/12548). The solution found there is conda update --all, but because I had Pytorch cuda I had to use the --no-channel-priority flag to prevent the pytorch_cuda10.2 from being overwritten. Now though, when I open Spyder, it warns me that I am missing the 'correct' Jedi, parso and qtconsole packages. Though, when I install the packages directly, it says those are already installed or are a more recent version of them. Also if I try to update them with conda, it wants to take me back to Spyder 3.3.6... Last, there's no kernel starting and I've tried conda install spyder-kernels, conda update ipykernels, and conda update setuptools (all various potential solutions I've seen). Not sure if this is relevant or helps, but my console reports 'libpng warning: bKGD: invalid' when I start Spyder.

**Comment by HapaxHypatia** [comment]
I have a fresh install of the latest version of Spyder (4.2.4) but still get this error. In my case, torch is being called by another library (allosaurus). It will run with no problems the first time, but I have to restart the kernel before it will work again

`Traceback (most recent call last):

  File "C:\projects\allosaurus test.py", line 8, in <module>
    from allosaurus.app import read_recognizer

  File "C:\Program Files\Spyder\pkgs\allosaurus\app.py", line 1, in <module>
    from allosaurus.am.utils import *

  File "C:\Program Files\Spyder\pkgs\allosaurus\am\utils.py", line 1, in <module>
    import torch

  File "C:\Program Files\Spyder\pkgs\torch\__init__.py", line 447, in <module>
    from .tensor import Tensor

  File "C:\Program Files\Spyder\pkgs\torch\tensor.py", line 13, in <module>
    from torch.overrides import (

  File "C:\Program Files\Spyder\pkgs\torch\overrides.py", line 1229, in <module>
    """

RuntimeError: function '_has_torch_function' already has a docstring`
