### ISSUE TITLE
TypeError: handle_get_file_code() got an unexpected keyword argument 'save_all'

### ISSUE THREAD

**Issue by mmahdavian** [spyder-ide/spyder#13715]
I get following error when I want to run any code in spyder in Anaconda.Do you know how can I resolve this?!:

```
This command failed to be executed because an error occurred while trying to get the file code from Spyder's editor. The error was:


An exception has occurred, use %tb to see the full traceback.

TypeError: handle_get_file_code() got an unexpected keyword argument 'save_all'
```
Anaconda

## Versions
* Spyder version: 4.1.3
* Python version: 3.6.9
* Qt version: 5.9.7
* Operating System name/version: Ubuntu

**Comment by ccordoba12** [comment]
Hey @mmahdavian, please update to Spyder 4.1.5 and try again. That should fix your problem.

**Comment by RobertDabbler** [comment]
Updating to 4.1.5 is what *caused* the problem, for me.  And it isn't fixed by downgrading back to 4.1.3 where I was before.

**Comment by wired4life4** [comment]
This happened to three of my computers as well. I fixed it by [completely uninstalling anaconda](https://docs.anaconda.com/anaconda/install/uninstall/) and reinstalling the latest version. Not a great solution but it worked for me.

**Comment by simaoafonso-pwt** [comment]
This sounds related to #13679 .

I was hit by this, and was able to fix it by installing `spyder-kernels==1.9.3`. I'm on `spyder==4.1.2`.

**Comment by ccordoba12** [comment]
This problem is solved by running

    conda install spyder-kernels 1.9.4

**Comment by texadactyl** [comment]
Same thing happened to me in a pip3 environment.  Reinstalling spyder-kernels worked for me (1.9.4 is the latest on pypi).

**Comment by nunobbrandao** [comment]
> This problem is solved by running
> 
> ```
> conda install spyder-kernels=1.9.4
> ```

I have got the issue but this solution did not solve the problem

**Comment by simaoafonso-pwt** [comment]
> I was hit by this, and was able to fix it by installing `spyder-kernels==1.9.3`

Note that the workaround for `spyder==4.1.2` is downgrading to this specific version.

**Comment by theinexorable** [comment]
Spyder: 4.1.4
spyder-kernels: 1.9.4
Python 3.7.7 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10 

So I'm trying to debug a file. With F9 (Run selection) it runs, but with F5 (Run file) or Ctrl+F5 (Debug file) the same error occurs. Now reading these comments I'm not sure whether I should downgrade spyder-kernels or Spyder.

**Comment by ccordoba12** [comment]
@theinexorable, Spyder 4.1.4 works with spyder-kernels 1.9.3, not with 1.9.4

**Comment by ehsanrs2** [comment]
update to the new version, its work for me
conda install spyder=4.1.5

**Comment by eusebiomarquesbenitez** [comment]
edit the File spydercustomize.py:
lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 463, in get_file_code function:
        file_code = frontend_request().get_file_code(
            filename, save_all=save_all)
to:
file_code = frontend_request().get_file_code(filename)

**Comment by DaneshJoy** [comment]
> update to the new version, its work for me
> conda install spyder=4.1.5

Worked for me!

**Comment by Qaazi** [comment]
C Cordoba....what the hell have u done to spyder?????
its has been two months it all messed up
nothing works
have tried re-installing it...re-installing spyder kernels, and all the help on stackoverflow
nothing works


spyder doesnt just work at all

i want to throw it into dustbin

**Comment by Cristianasp** [comment]
Got the same problem after upgrading to 4.1.3 and moved to 4.1.5 and it is now ok. thanks for the tip.

**Comment by reddyanjali** [comment]
> 
> 
> update to the new version, its work for me
> conda install spyder=4.1.5

This worked for me! Thank You!

**Comment by gabrielarcangelbol** [comment]
Thanks!

> update to the new version, its work for me
> conda install spyder=4.1.5

Thanks!

**Comment by vl2376** [comment]
Getting this problem with spyder 4.1.6 and spyder-kernels 1.9.4

**Comment by vl2376** [comment]
I dont know if it was uninstalling / reinstalling spyder or downgrading but now it works with 4.1.5

**Comment by Asmedeus998** [comment]
> update to the new version, its work for me
> conda install spyder=4.1.5

Thanks it work now. In case someone failed to insatll version 4.1.5 try to uninstall **spyder completely** then install it again.

**Comment by kmanflickr** [comment]
yes upgrade from 4.1.3 to 4.1.5 works. Thanks a lot!!!

**Comment by texadactyl** [comment]
@kmanflickr 
The latest version is 4.2.4 which has resolved a number of irritants.  I would recommend installing it.

**Comment by kmanflickr** [comment]
> @kmanflickr
> The latest version is 4.2.4 which has resolved a number of irritants. I would recommend installing it.

Hey Thanks for your help. I think 4.2.3 is the last for windows OS. 4.2.4 is probably mac only

**Comment by texadactyl** [comment]
4.2.4 runs on MacOS and Linux.  I have no idea about Windows.

**Comment by OlumideOlumayegun** [comment]
> 
> 
> update to the new version, its work for me
> conda install spyder=4.1.5

Thanks, this works for me
