### ISSUE TITLE
Debug error : Step inside (ctrl+f11) does not work

### ISSUE THREAD

**Issue by MAfarrag** [spyder-ide/spyder#13868]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When debugging the code and trying to step inside a module method with ctrl+f11 it does not work
[debugerror](https://user-images.githubusercontent.com/33198578/94372479-3113b380-00fe-11eb-861f-b629c9d38bbc.gif)

### What steps reproduce the problem?

1. debug any code and try to step inside any imported module method

### What is the expected output? What do you see instead?
spyder should open the module and execute line by line every time you press ctrl+f10

```

## Versions
* Spyder version: 4.1.5
* Python version: 3.7.8
* Qt version: 5.12.6
* PyQt version: 5.12.3
* Operating System name/version: windows 10

### Dependencies
```
# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.6 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.0 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.2 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.1.2 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @MAfarrag, thanks for reporting. I really don't understand why this is happening.

@impact27, could you take a look at this one?

**Comment by impact27** [comment]
Could you send a code that triggers the bug? It looks like you are trying to enter into a library. several things can happen:
 - If the library code is not python (but C or something), the debugger can't show anything
 - If you have the hide library option enabled, the libraries are hidden

**Comment by MAfarrag** [comment]
just try to debug any simple code like reading a text file with pandas and try to step inside the read_csv method spyder should open the file where the read_csv method exist and should execute line by line as long and you press ctrl+f10, but instead, no file is opened and the console shows "--call--" then "--return--" till the method totally returns to the main file.

![debugerror](https://user-images.githubusercontent.com/33198578/94423942-babc9300-0189-11eb-8a99-d8b605b54fdb.gif)

**Comment by ccordoba12** [comment]
Most probably (as @impact27 said), `pandas.read_csv` is a C or Cython function, so you can't step inside it to see how it works.

**Comment by MAfarrag** [comment]
@ccordoba12 no it is not a C function I have it installed in another machine and the step inside (ctrl+f11) works fine 
and here are the specification of the other machine

## Versions
* Spyder version: 4.1.3
* Python version: 3.7.7
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: windows 10

### Dependencies
```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.17.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.6.0 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.0 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.3 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)

```

**Comment by MAfarrag** [comment]
@impact27 @ccordoba12 any update on this issue?

**Comment by ccordoba12** [comment]
Please update to our latest release (4.1.5) and try again.

**Comment by impact27** [comment]
I can't reproduce on windows. The only explaination I have is that you have the "ignore libraries" option enabled.

**Comment by MAfarrag** [comment]
> I can't reproduce on windows. The only explanation I have is that you have the "ignore libraries" option enabled.

yes that actually was the problem, thanks now the problem is solved

**Comment by DaryMile** [comment]
I have similar problem.
I make a remote connection with nanopi using remote spyder kerner.
I can run and debug files,
BUT, when i want to step into (CTRL+F11) function which locate in another file, Spyder Editor DON'T open this file. But debug proccess still continued (I can see in in Variable Explorer).

I have this problem only with remote kernels.

Versions on nanopi:
spyder-kernels    2.5.2
Python 3.10.12

Versions on Linux OS:
spyder-kernels 2.5.2.
Python 3.10.12
