### ISSUE TITLE
Spyder 4 extremely slow writing on text editor in MacOS Big Sur

### ISSUE THREAD

**Issue by silvestre125** [spyder-ide/spyder#14525]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [X] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [X] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When I write in the code editor in Spyder, letters are displayed extremely slow, I mean I can write the following: "jsdhfakljhdsfjkhsdkjhfkjdshfjkdshkjfh" and it'll take about 5-8 seconds in show it in the text editor.

### What steps reproduce the problem?

1. The problem only affects to Spyder>3.3.6 in MacOS Big Sur on a clean Anaconda3 installation.

## Versions

* Spyder version: spyder=4.2.0
* Python version: python=3.8.5
* Qt version: qt=5.9.7
* PyQt version: pyqt=5.9.2
* Operating System name/version: MacOS Big Sur 11.1

### Dependencies

# Mandatory:
applaunchservices >=0.1.7       :  0.2.1 (OK)
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=4.0                   :  7.19.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.2 (OK)
pygments >=2.0                  :  2.7.3 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.1;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.1.1             :  0.3.0 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=4.7.7               :  4.7.7 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  51.0.0.post20201207 (OK)
sphinx >=0.6.6                  :  3.4.1 (OK)
spyder_kernels >=1.10.0;<1.11.0 :  1.10.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  0.10.4 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  None (NOK)
numpy >=1.7                     :  None (NOK)
pandas >=1.1.1                  :  None (NOK)
scipy >=0.17.0                  :  None (NOK)
sympy >=0.7.3                   :  None (NOK)
![2021-01-02 14 01 00](https://user-images.githubusercontent.com/46159929/103457979-f6747500-4d03-11eb-931d-31d90c411af6.gif)

**Comment by ccordoba12** [comment]
Hey @silvestre125, thanks for reporting. This problem is known and already solved in our latest version (4.2.1), but only if you install Spyder from our [DMG](https://github.com/spyder-ide/spyder/releases/download/v4.2.1/Spyder.dmg) or following the instructions in our [FAQ](https://docs.spyder-ide.org/current/faq.html#troubleshooting-macos-bigsur) about it.

Please try any of those and let us know if it works for you.

**Comment by silvestre125** [comment]
Thanks for the fast reply. It works perfectly from the DMG although I've tried the suggestion in your FAQs, and it doesn't work for me.

**Comment by ccordoba12** [comment]
Ok, glad to know that you can use our DMG in the meantime.

**Comment by 9harshit** [comment]
> Hey @silvestre125, thanks for reporting. This problem is known and already solved in our latest version (4.2.1), but only if you install Spyder from our [DMG](https://github.com/spyder-ide/spyder/releases/download/v4.2.1/Spyder.dmg) or following the instructions in our [FAQ](https://docs.spyder-ide.org/current/faq.html#troubleshooting-macos-bigsur) about it.
> 
> Please try any of those and let us know if it works for you.

Hello @ccordoba12, I update Spyder to 4.2.1 in Anaconda Navigator but the problem still persists. The issue has not been resolved

**Comment by leet0rz** [comment]
Still an issue in windows. it lags a lot.

**Comment by brilund** [comment]
Still an issue on Mac.

**Comment by edmondja** [comment]
Still an issue for spyder 4 and 5

**Comment by MassimoPaloscia** [comment]
Still an issue for spyder 5 on Mac. It lags a lot only on the text editor, for the terminal and other things it work very well.

**Comment by ccordoba12** [comment]
The only known workaround to make Spyder work in Big Sur is to download our [DMG installer](https://github.com/spyder-ide/spyder/releases/latest) and then connect it to your conda environments by following our FAQ [here](http://docs.spyder-ide.org/current/faq.html#using-existing-environment).

All users that tried this have reported it solves the lags for them.
