### ISSUE TITLE
Problem Spyder console

### ISSUE THREAD

**Issue by isr-git** [spyder-ide/spyder#15418]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/usr/lib/python3/dist-packages/qtconsole/console_widget.py", line 413, in eventFilter
    return self._event_filter_console_keypress(event)
  File "/usr/lib/python3/dist-packages/spyder/widgets/ipythonconsole/debugging.py", line 108, in _event_filter_console_keypress
    self)._event_filter_console_keypress(event)
  File "/usr/lib/python3/dist-packages/qtconsole/frontend_widget.py", line 381, in _event_filter_console_keypress
    return super(FrontendWidget, self)._event_filter_console_keypress(event)
  File "/usr/lib/python3/dist-packages/qtconsole/console_widget.py", line 1146, in _event_filter_console_keypress
    self.execute(interactive = not shift_down)
  File "/usr/lib/python3/dist-packages/qtconsole/history_console_widget.py", line 47, in execute
    source, hidden, interactive)
  File "/usr/lib/python3/dist-packages/qtconsole/console_widget.py", line 605, in execute
    complete, indent = self._is_complete(source, interactive)
  File "/usr/lib/python3/dist-packages/qtconsole/frontend_widget.py", line 280, in _is_complete
    reply = kc.shell_channel.get_msg(block=True, timeout=self.is_complete_timeout)
TypeError: get_msg() got an unexpected keyword argument 'block'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.9
* Qt Versions: 5.9.5, PyQt5 5.10.1 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.8.1 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.19.5 (OK)
sphinx >=0.6.6   :  1.6.7 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.18.0 (OK)
psutil >=0.3     :  5.4.2 (OK)
nbconvert >=4.0  :  6.0.7 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  7.16.1 (OK)
pylint >=0.25    :  1.8.3 (OK)

```

**Comment by ccordoba12** [comment]
Hey @isr-git, thanks for reporting. Unfortunately we don't maintain Spyder 3 anymore. This problem should be fixed in our latest 4 version though. To have it you need to download and install Anaconda Prompt and then open a terminal and run there these commands:

    conda update anaconda
    conda install spyder=4.2.5

Please do that and let us know if it works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by ENIAC-6** [comment]
I am having the same issue as described here. 
* Spyder version: 5.4.1 64-bit
* Python version: 3.10.9
* Qt version: 5.15.2
* PyQt version: 5.15.7
* Operating System name/version: Windows 10

- I'm having the same issue as #https://github.com/spyder-ide/spyder/issues/14818
- I've followed the steps outlined here but I still get an invalid path error when trying to point Spyder to a cloned arcgispro-py3 environment: #https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder#the-naive-approach
- I found the above post at the ESRI Community Site: https://community.esri.com/t5/arcgis-pro-questions/arcgis-pro-2-9-2-unable-to-install-spyder/td-p/1162833/page/2

I have also tried: 
```
conda update anaconda
conda install spyder=4.2.5
```
![image](https://user-images.githubusercontent.com/22527868/233873555-77e6c45d-a1f9-463e-a0ea-f768139a420c.png)

As well as: 
`conda install -c conda-forge spyder-kernels=2.1.3`

Which ran successfully, but  am still getting the invalid path error when I try to point to the interpreter in my arcgispro-py3 cloned environment.

My takeaway from the ESRI Dev Summit was that the dependencies for Spyder and the arcgispro-py3 are in conflict and I was basically told to use Visual Studio Code. I love Spyder and am tying to hang on to it but can't get it running on a new computer with ArcGIS Pro 3.1. 

Do you have any suggestions?

**Comment by ccordoba12** [comment]
@ENIAC-6, if I understood you correctly, you're trying to install Spyder 4.2.5 so you can connect it to an ArcGIS Pro 3.1 environment?

**Comment by ENIAC-6** [comment]
> @ENIAC-6, if I understood you correctly, you're trying to install Spyder 4.2.5 so you can connect it to an ArcGIS Pro 3.1 environment?

@ccordoba12, apologies for the delay. That is correct. I would like to use any version of Spyder with an ArcGIS Pro 3.1 environment. Thank you!

**Comment by ccordoba12** [comment]
Ok, in that case I suggest to download our Windows installer for 4.2.5 from here:

https://github.com/spyder-ide/spyder/releases/tag/v4.2.5

That shouldn't give you any error.
