### ISSUE TITLE
High typing latency issues on MacOS Big Sur

### ISSUE THREAD

**Issue by moonj94** [spyder-ide/spyder#16497]
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [x ] Reset preferences with ``spyder --reset``
    * [ x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ x] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Ever since upgrading to Big Sur, I have been having some issues with the Spyder editor. It's not too bad for a little bit and then suddenly there is high typing latency. I have tried the various steps outlined in previous threads, including:

```
conda activate spyder-dev
export QT_MAC_WANTS_LAYER=1
spyder
```

However, nothing seems to be working. I have also updated qt and pyqt.

## Versions

* Spyder version: 5.0.5
* Python version: 3.7.11
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: 
Mac OS Big Sur, version 11.5.1

**Comment by steff456** [comment]
Hi @moonj94,

Can you please update to our latest release 5.1.5 and see if it gets better? Please let me know how this go.

**Comment by moonj94** [comment]
Hi @steff456 I am attempting to install 5.1.5 through conda, but there appears to be many conflicting dependencies. Can you tell me how I can properly install this? I am hesitant on downloading the .dmg file because I have previously attempted this, and the app could not even be moved to the Applications folder nor open.

**Comment by steff456** [comment]
If you want to use conda, then let's create a new environment and install Spyder there to see if it works, so

```
conda create -n test-env python=3.7 -c conda-forge
conda activate test-env
conda install spyder=5.1.5 -c conda-forge
spyder
```

Please note that we are going to use the conda-forge channel because the packages are available there. So please if you are going to install more dependencies to this environment always use the `-c conda-forge` flag.

Please let me know how this go.

**Comment by eshanking** [comment]
Hi @steff456 , I have successfully installed Spyder 5.1.5 on my iMac and M1 MacBook Pro. The typing latency persists on my iMac, but it is resolved on my MacBook. Both machines have Big Sur 11.6. There is significant typing latency in large and small files and lag when scrolling or adjusting screen size. Do you have any advice?

**Comment by steff456** [comment]
@eshanking does this happens as soon as you start an instance of Spyder or after a while of using it?

**Comment by eshanking** [comment]
@steff456 , I haven't noticed any typing latency since restarting my iMac. There is still scrolling latency, but this isn't too bad. 

Thanks for your help.

**Comment by CrispBull** [comment]
I'm still having this issue. I've restarted my mac multiple times, closed any other heavy running program I have (Android Studio in particular), and I still have this latency with typing and scrolling.

**Comment by ccordoba12** [comment]
@CrispBull, please try our latest Mac app, it should work much better now:

https://github.com/spyder-ide/spyder/releases

**Comment by CrispBull** [comment]
I am using Spyder via Anaconda, I'm not so familiar with how it works, how do I update the Spyder to this version as I can't see this version in the Spyder versions. I'm currently on 5.1.5

**Comment by ccordoba12** [comment]
That's why I suggested to try our Mac app because Anaconda takes months to update Spyder. The app is totally self-contained, so it won't interfere with your current Anaconda installation.

**Comment by CrispBull** [comment]
Awesome! Thanks

**Comment by 4rron** [comment]
Just recently got back into Spyder on a new M1 Max MacBook and ran into this issue. Removing Kite from the Completion and Linting settings removed all typing latency for me.

_Settings > Completion and Linting >_ 
**Uncheck** _"Notify me when Kite can provide missing completions (but is unavailable)"_
**Uncheck** _"Enable Kite provider"_

**Comment by ccordoba12** [comment]
Closing because this is quite old now and we've done many improvements to fix the typing latency since.
