### ISSUE TITLE
Spyder 5 can not be updated - Dependencies issue?

### ISSUE THREAD

**Issue by jeng87** [spyder-ide/spyder#17386]
[Issue report checklist.pdf](https://github.com/spyder-ide/spyder/files/8117513/Issue.report.checklist.pdf)

**Comment by ccordoba12** [comment]
Hey @jeng87, thanks for reporting. That is not a dependencies problem, it's due to the fact that Anaconda has not updated packages for our latest version yet.

Until that happens, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open your terminal and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

After that, you can connect Spyder to your base environment by following these instructions:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment

**Comment by jeng87** [comment]
Hi, Thank you for the help. I have made new environment with conda-forge packages for spyder, and I follow the step to connect spyder to the environment that I need to work with. But another issue pop up like below showing in the spyder console. And I install spyder-kernels 2.2, but still not solving the problem. Can you please help me with this new issue. Thank you. 

The Python environment or installation whose interpreter is located at
    /home/lorizeltser/anaconda3/envs/ClearMapStable/bin/python
doesn't have the spyder‑kernels module or the right version of it installed (>= 2.2.1 and < 2.3.0). Without this module is not possible for Spyder to create a console for you.

You can install it by activating your environment (if necessary) and then running in a system terminal:
    conda install spyder‑kernels=2.2
or
    pip install spyder‑kernels==2.2.*

**Comment by jeng87** [comment]
And I don't understand. I installed anaconda in Nov last year, which should be their newest version. Why I would have package out data problem. Thank you.

**Comment by ccordoba12** [comment]
Hey @jeng87, you said:

> But another issue pop up like below showing in the spyder console

To solve this problem, you also need to install spyder-kernels from conda-forge, like this

    conda install -c conda-forge spyder-kernels

If you get errors in your current environment after doing that, please create a new environment with spyder-kernels and the packages you need to use (e.g. Scikit-learn):

    conda create -n myenv -c conda-forge spyder-kernels scikit-learn

> And I don't understand. I installed anaconda in Nov last year, which should be their newest version. Why I would have package out data problem. Thank you.

I know this is very confusing, but the problem is Anaconda takes a lot of time to update Spyder. For instance, we released our 5.1.5 version six months ago, but that's the last one available in Anaconda. Whereas our latest version (5.2.2) was released a month ago.

This has become the norm in Anaconda (before they took at most a week to upload packages for a new version), which is why we now recommend our users to use Conda-forge instead.

Let us know if there's something else we can help you with.

**Comment by jeng87** [comment]
[jeng87.zip](https://github.com/spyder-ide/spyder/files/8119268/jeng87.zip)
Hi @ccordoba12 I upload the environment file in here. And the spyder-kernels error still exist. If you need to run the script I am using. I can upload them, but it will take a while because I have to upload lots of raw data. thank you.

**Comment by jeng87** [comment]
https://christophkirst.github.io/ClearMap2Documentation/html/installation.html#cloning
@ccordoba12 Here is the pipeline of installation of the tool I am using, and seems like the environment file is the frozen package versions

**Comment by jeng87** [comment]
Hi @ccordoba12,

I have fix this problem by uninstalling an alternative environment file first with flexible package dependencies. The previous environment is created with all frozen package dependencies, and thus it seems I couldn't do anything at that time when I was trying to use the newest Spyder. Thank you so much helping me with this issue.

**Comment by ccordoba12** [comment]
Great! I'm really glad you were able to solve your problem. And thanks for letting us know about it.
