### ISSUE TITLE
Layout is broken sometimes when many consoles are open

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#19084]
## Problem Description

When I started to work on PR #19068, I noticed that sometimes the layout is not preserved correctly when Spyder is closed. This means that it looks like this when it's started again

![image](https://user-images.githubusercontent.com/365293/185014063-656ba6a9-fec9-4a09-bb12-e7c0a635716c.png)

### What steps reproduce the problem?

1. Open many consoles in Spyder
2. Close Spyder
3. Open Spyder again and notice that the layout is broken 

### What is the expected output? What do you see instead?

The layout is preserved in the next session.

**Comment by jitseniesen** [comment]
Nice! I noticed the same (?) problem, but without having to open many consoles and seemingly not consistently. I did not investigate.

**Comment by ccordoba12** [comment]
Thanks for the confirmation @jitseniesen! I think PR #19085 should solve this problem for good, but let us know if that's the case for you too after I merge it (I think that PR needs to be part of 5.x to test it because the bug is elusive).

**Comment by jitseniesen** [comment]
@ccordoba12 Actually, I think it may be a different issue that I came across. On my Linux system, if I close Spyder with Alt-F4 (Gnome shortcut), it screws up the layout when I start it again exactly as in your picture, but not if I close with Ctrl-Q (the Spyder shortcut). Unfortunately your PR does not seem to fix this.

**Comment by ccordoba12** [comment]
Ok, that's very strange, but please open a new issue about it so we can take a look at it for 5.3.4.
