### ISSUE TITLE
Your IPython frontend and kernel versions are incompatible

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2006]
_From [goldmun...@gmail.com](https://code.google.com/u/113805554964965149093/) on 2014-10-14T09:02:04Z_

Spyder Version:  2.3.1
Python Version:  2.7.8
Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.1 on Darwin
pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
IPython >=0.13  :  2.2.0 (OK)
pygments >=1.6  :  1.6 (OK)
pandas >=0.13.1 :  0.14.1 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
psutil >=0.3    :  2.1.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  1.3.0 (OK) 

What steps will reproduce the problem?

 1. Install Spyder
2. Set Console>Advanced Settings>Python executable = /usr/local/bin/python
3. Click OK
4. Open IPython console 

What is the expected output? What do you see instead?

 I would expect an IPython console, I see the following message:

An error ocurred while starting the kernel
Either:
Your IPython frontend and kernel versions are incompatible or
You don't have IPython installed in your external interpreter.
In any case, we're sorry but we can't create a console for you. 

Please provide any additional information below

. System:
Mac OS X Mavericks
Python and IPython installed with Homebrew at the latest versions

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2006_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-14T15:25:40Z_

I'll try to fix it for our next version

**Labels:** MS-v2.3.2 Cat-IPythonConsole

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-31T15:07:53Z_

**Labels:** -MS-v2.3.2 MS-v2.3.3

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-18T17:51:35Z_

issue #1927 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [santiago...@gmail.com](https://code.google.com/u/101954920107976352849/) on 2014-12-02T01:56:13Z_

This is also happening to me (Mavericks, Homebrewed Python + IPython, spyder-2.3.1-py27.dmg).

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-12-04T13:13:51Z_

Damn! I haven't looked at this code in a long time so it's probably a case we're not considering introduced in recent IPython versions.

I'll fix it for sure in 2.3.3

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-12-17T13:22:06Z_

I can't reproduce it on Linux, so it's specific to our dmg

**Labels:** OpSys-OSX

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-09T17:26:53Z_

This issue was closed by revision 18abf47f106d .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [sad...@gmail.com](https://code.google.com/u/113705236299871724793/) on 2015-01-09T18:13:24Z_

So, is it fixed in this version? Do we need to redownload the package? Thanks !

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-09T18:56:49Z_

Nop, sorry. You'll have to wait until 2.3.3 is released (in about two weeks)

**Comment by spyder-issues-migrator** [comment]
_From [sad...@gmail.com](https://code.google.com/u/113705236299871724793/) on 2015-01-09T20:53:14Z_

Ok, thanks !

-Talha

**Comment by santjaqo** [comment]
Hi Carlos,
I am now in Yosemite, same brewed python, but using the brand new Spyder 2.3.3 version, installed from the github dmg. I still cannot use Spyder with my brewed /usr/local/bin/python nor any other python in virtualenv's. Could you please help me out to set Spyder to work in my Mac?

**Comment by ccordoba12** [comment]
@santjaqo, are you getting this same error? or something else?

**Comment by santjaqo** [comment]
Dear Carlos, thanks for your quick answer.

The message is different but the situation is the same: the IPython console
does not load. The message I get is 'An error ocurred while starting the
kernel'.

Regards, Santiago

**Comment by ccordoba12** [comment]
You're right. Please open a new issue so that I don't forget to solve it 
for 2.3.4.

**Comment by santjaqo** [comment]
Hi Carlos. I just did so. The issue number is 2227.

**Comment by robhawkins** [comment]
I get this error in a virtual environment using Python 2.7.6 , IPython 4.03,  Spyder 2.3.8,  Ubuntu 14.04
