### ISSUE TITLE
Two Spyder icons on Windows taskbar

### ISSUE THREAD

**Issue by pscobey** [spyder-ide/spyder#20791]
### What steps will reproduce the problem?

Despite trying several Google-suggested solutions, updating Spyder, and removing/readding the Spyder icon to the Windows 10 taskbar I have been unable to prevent the appearance of the second Spyder icon when I start Spyder, which is particularly annoying given that I have a two-layer taskbar! Any help getting rid of that second icon would be much appreciated as I am constantly having to switch between programs while teaching online.

## Versions

* Spyder version: 5.4.2  (conda)
* Python version: 3.9.16 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<9.0.0       :  8.12.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  23.13.1 (OK)
nbconvert >=4.0               :  6.5.4 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<3.0           :  2.16.2 (OK)
pylint_venv >=2.1.1           :  2.3.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.7.1;<1.8.0          :  1.7.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.2 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.0 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  65.6.3 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.4.2;<2.5.0 :  2.4.2 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.7.1 (OK)
numpy >=1.7                   :  1.23.5 (OK)
pandas >=1.1.1                :  1.5.3 (OK)
scipy >=0.17.0                :  1.10.1 (OK)
sympy >=0.7.3                 :  1.11.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @pscobey, thanks for reporting. I thought we have already fixed this problem, but it seems that's not the case.

@dalthviz, do you remember about this problem? I think you took a look at it before, right?

**Comment by dalthviz** [comment]
Checking seems like this is working for the standalone Windows installer and a issue about the behavior was closed as part of a PR fixing but only for the Windows installer (https://github.com/spyder-ide/spyder/pull/14219). So seems like the issue remains if you are using conda. In the initial issue (https://github.com/spyder-ide/spyder/issues/1983) seems like the conclusion was that you need to set a AppUserModelID for the shortcut (which is something that requires admin privileges?).

**Comment by ccordoba12** [comment]
Ok, I see. Thanks @dalthviz for your clarifying comment. Could it be possible to add an entry to one of our menus to call `AppUserModelID` on Spyder's link file in admin mode?

@mrclary, I think we also need to add to this our new Windows installer so that it has feature parity with the current one. So, another option would be to check if `menuinst` can handle this (that way it'd work for Spyder, Napari and any other application).

**Comment by mrclary** [comment]
Okay, I do see both icons with the conda-based installer on my Windows VM, so `menuinst` has not addressed this.

@jaimergp, is it possible for `menuinst` to address this, or is this handled by an nsis template that we should provide? As an aside, should `menuinst` prevent `cmd` windows from opening when launching applications from the shortcut in Windows?

**Comment by dalthviz** [comment]
> Could it be possible to add an entry to one of our menus to call AppUserModelID on Spyder's link file in admin mode?

Not sure to be honest, we will need to check.  Seems like some info in the original issue is available but it requires not only admin privileges but also restarting `explorer.exe` (or restarting you PC) and also knowing the location of the shortcut (which can vary depending on the installation I think? 🤔 ) : https://github.com/spyder-ide/spyder/issues/1983#issuecomment-622293126

Just in case, for the Windows installer with pynsist the pinging was achived by adding this to the nsis template (if I understand correctly what was done there): 
https://github.com/dalthviz/spyder/blob/739873b8e0d1aa6df94d41ec17575eb9d1c8260e/installers/Windows/assets/nsist/spyder.nsi#L113-L114

**Comment by ccordoba12** [comment]
Thanks for looking into this @mrclary. I think doing it for our Windows installer is fine for now.

**Comment by jaimergp** [comment]
> Okay, I do see both icons with the conda-based installer on my Windows VM, so `menuinst` has not addressed this.
> 
> @jaimergp, is it possible for `menuinst` to address this, or is this handled by an nsis template that we should provide? As an aside, should `menuinst` prevent `cmd` windows from opening when launching applications from the shortcut in Windows?

We can add some code in `menuinst` for this. Can you open an issue in `conda/menuinst` with the full context? I'll address it at some point, but we have other feature requests (URL / file type association) in the roadmap first 😬
