### ISSUE TITLE
Class 2023 Google meet

### ISSUE THREAD

**Issue by GitKia1392** [spyder-ide/spyder#21399]
### What steps will reproduce the problem?

So it was a normal day until i opened Spyder IDE, I opened a new python file but when i looked at the IPython Consle i was shocked, the errno(or error) was:
FileNotFoundError: [Errno 2] No usable temporary directory found in ['C:\\Users\\alexm\\AppData\\Local\\Temp', 'C:\\Users\\alexm\\AppData\\Local\\Temp', 'C:\\Users\\alexm\\AppData\\Local\\Temp', 'C:\\WINDOWS\\Temp', 'c:\\temp', 'c:\\tmp', '\\temp', '\\tmp', 'C:\\Users\\alexm']
Then I did disk cleanup in the Temp files in C:\, Took the permissions, Serched for the fix, REINSTALLED Spyder and even with the reINSTALL it still wouldn't budge to fix the bug either, So if you could tell me the fix or tell me im being stupid then pls tell me

Thank you for your time
Kiamehr Eskandari

### Traceback
```python-traceback
Traceback (most recent call last):
  File "K:\Spyder IDE\pkgs\spyder\plugins\projects\plugin.py", line 430, in create_new_project
    self._create_project(root_path, project_type_id=project_type)
  File "K:\Spyder IDE\pkgs\spyder\plugins\projects\plugin.py", line 439, in _create_project
    project = project_type_class(
  File "K:\Spyder IDE\pkgs\spyder\plugins\projects\api.py", line 49, in __init__
    self.config = self.create_config(path)
  File "K:\Spyder IDE\pkgs\spyder\plugins\projects\api.py", line 108, in create_config
    return ProjectMultiConfig(
  File "K:\Spyder IDE\pkgs\spyder\config\user.py", line 749, in __init__
    self._configs_map[name] = config_class(**new_kwargs)
  File "K:\Spyder IDE\pkgs\spyder\config\user.py", line 180, in __init__
    super(UserConfig, self).__init__(name=name, path=path)
  File "K:\Spyder IDE\pkgs\spyder\config\user.py", line 55, in __init__
    os.makedirs(osp.dirname(self._path))
  File "os.py", line 213, in makedirs
  File "os.py", line 223, in makedirs
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\alexm\\OneDrive\\Classes Google Meet No.1 2023\\Classes Google Meet No.1 2023'
```

## Versions

* Spyder version: 5.4.5  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.22631-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                                                        :  1.4.1 (OK)
chardet >=2.0.0                                                             :  5.2.0 (OK)
cloudpickle >=0.5.0                                                         :  2.2.1 (OK)
cookiecutter >=1.6.0                                                        :  2.3.0 (OK)
diff_match_patch >=20181111                                                 :  20230430 (OK)
intervaltree                                                                :  None (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0,!=8.11.0,!=8.12.0,!=8.12.1 :  8.12.2 (OK)
jedi >=0.17.2,<0.19.0                                                       :  0.18.2 (OK)
jellyfish >=0.7                                                             :  1.0.0 (OK)
jsonschema >=3.2.0                                                          :  4.19.0 (OK)
keyring >=17.0.0                                                            :  24.2.0 (OK)
nbconvert >=4.0                                                             :  7.8.0 (OK)
numpydoc >=0.6.0                                                            :  1.5.0 (OK)
paramiko >=2.4.0                                                            :  3.3.1 (OK)
parso >=0.7.0,<0.9.0                                                        :  0.8.3 (OK)
pexpect >=4.4.0                                                             :  4.8.0 (OK)
pickleshare >=0.4                                                           :  0.7.5 (OK)
psutil >=5.3                                                                :  5.9.5 (OK)
pygments >=2.0                                                              :  2.16.1 (OK)
pylint >=2.5.0,<3.0                                                         :  2.17.5 (OK)
pylint_venv >=3.0.2                                                         :  3.0.2 (OK)
pyls_spyder >=0.4.0                                                         :  0.4.0 (OK)
pylsp >=1.7.4,<1.8.0                                                        :  1.7.4 (OK)
pylsp_black >=1.2.0,<3.0.0                                                  :  1.3.0 (OK)
qdarkstyle >=3.0.2,<3.2.0                                                   :  3.1 (OK)
qstylizer >=0.2.2                                                           :  0.2.2 (OK)
qtawesome >=1.2.1                                                           :  1.2.3 (OK)
qtconsole >=5.4.2,<5.5.0                                                    :  5.4.3 (OK)
qtpy >=2.1.0                                                                :  2.4.0 (OK)
rtree >=0.9.7                                                               :  1.0.1 (OK)
setuptools >=49.6.0                                                         :  68.1.2 (OK)
sphinx >=0.6.6                                                              :  7.1.2 (OK)
spyder_kernels >=2.4.4,<2.5.0                                               :  2.4.4 (OK)
textdistance >=4.2.0                                                        :  4.5.0 (OK)
three_merge >=0.1.1                                                         :  0.1.1 (OK)
watchdog                                                                    :  3.0.0 (OK)
zmq >=22.1.0                                                                :  25.1.1 (OK)

# Optional:
cython >=0.21                                                               :  3.0.2 (OK)
matplotlib >=3.0.0                                                          :  3.7.2 (OK)
numpy >=1.7                                                                 :  1.24.4 (OK)
pandas >=1.1.1                                                              :  2.0.3 (OK)
scipy >=0.17.0                                                              :  1.10.1 (OK)
sympy >=0.7.3                                                               :  1.12 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2                                        :  1.2.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @GitKia1392, thanks for reporting. I think your problem has to with the name of the directory where you're trying to create a Spyder project:

    C:\Users\alexm\OneDrive\Classes Google Meet No.1 2023\Classes Google Meet No.1 2023

Please rename it to

    C:\Users\alexm\OneDrive\Classes Google Meet No1 2023\Classes Google Meet No1 2023

(I just removed the dots in `No.1`) and try again.

That should solve the issue for you but let us know if it really does.

**Comment by GitKia1392** [comment]
Ok thanks then I will try that and I will notify you.

Thanks

**Comment by GitKia1392** [comment]
Nah, Still the same error but no offense, But No bro it says The C:\Users\alexm... Not like your 'removing the dots' thing.
But I mean I cleared THE ENTIRE TEMPORARY FILES(which cost me 26 GB btw).  Which was a little dumb of me to do i guess but I still tried though.

Thanks for advising but if there's No solution within 2024 then I will close this issue.

**Comment by GitKia1392** [comment]
OK I found the Solution to it. It was **Windows Unauthorized Folder Protection**. The reason for this is because Spyder couldn't find a TEMP directory is because Windows was thinking it was apparently trying to 'attack' the C:\ drive. Since Spyder couldn't LOOK inside the C:\ drive to check if there was a temp Directory or not but it didn't have permissions to READ it so...

Thanks @ccordoba12 for advising me for help

**Comment by ccordoba12** [comment]
No problem and thanks for letting us know about it. I'm really glad you were able to find the solution to this problem and can use Spyder again.
