### ISSUE TITLE
Smart cursor and backspace/delete-> inconsistend behaviour when at end of line

### ISSUE THREAD

**Issue by skjerns** [spyder-ide/spyder#22218]
## Problem Description

When shifting lines, the smart cursor behaves inconsistently.

Consider the following example where I want to remove the last digit of each variable (i.e. the 1,2,3,4)

```
var1
var2
var3
var4
```

Here, I have the cursor at `var1`, press backspace, then down, and I would expect that the cursor lands on the end of the line. However, it lands between `var` and `2`. So for the next removal, I need to press `delete` to delete the `2`. However, when pressing down now, the cursor jumps to the end of line! So for removing the `3`, I need to press backspace again.

This behaviour is inconsistend.

Solution: Either keep in the same column for both backspace of delete, or always move to end of line of we are at the end of line?

![Animation](https://github.com/spyder-ide/spyder/assets/14980558/46f1fba6-5eca-4a39-8e0e-8cc6601b99e1)

```
var1
var2
var3
var4
```

Put cursor to `var1[CURSOR]`. Remove with backspace. Then try to delete `2`. etc

## Versions

* Spyder version: 5.1.1
* Python version: N/A
* Qt version: N/A
* PyQt version: N/A
* Operating System name/version: win/linux

**Comment by dalthviz** [comment]
Hi @skjerns thank you for the feedback! Checked this on Windows using Spyder 5.5.5 from the standalone installer and I'm unable to reproduce. For me, after the first backspace, the cursor column position doesn't change and I can continuously use `delete`  to remove things:

![delete_cursor_column](https://github.com/spyder-ide/spyder/assets/16781833/3e242355-9433-47e3-bae0-bff935dd1b88)

Could it be possible for you to check with a more recent Spyder version? Seems like you are using a quite old one (5.1.1) so maybe the behavior you are experiencing was fixed at some point 🤔 

Let us know!

**Comment by skjerns** [comment]
Ah, sorry, my bad. I am indeed using 5.5.4, no idea why I wrote 5.1.1.

I've updated to 5.5.5 but the problem persists :-/

**Comment by dalthviz** [comment]
Thanks for the feedback @skjerns ! If updating didn't work maybe the issue could be related with an Editor config (I think there are a couple of preferences realted with the handling of backspace :thinking:) In my setup I have the Editor preferences set in this way:

![image](https://github.com/user-attachments/assets/c7832c0b-8f7b-479e-8af0-6ccbe5e3639d)![image](https://github.com/user-attachments/assets/bca7732b-221d-484b-8f39-3ad0020a6cdb)![image](https://github.com/user-attachments/assets/98676b1b-f675-43a7-8d10-4f0afbc7714c)![image](https://github.com/user-attachments/assets/575b9215-38bb-433e-999e-da29486f7505)

Is there something different in your setup? Could it be possible for you to share your Spyder preferences files to see if I'm able to reproduce this when using them? Let us know!

**Comment by skjerns** [comment]
All settings the same except for `highlight occurances`, `show indent guides` and `scroll past end`

I reverted to your settings and then turned on my initial settings again. And suddenly the problem is gone 🤯 no idea what caused the problem.

<details>
  <summary>Screenshots</summary>
![image](https://github.com/user-attachments/assets/f92c2c2b-1a6d-491d-8d63-b601eae7f480)
![image](https://github.com/user-attachments/assets/ac1c422b-98f7-44ab-a8b1-ee02b93fb89c)
![image](https://github.com/user-attachments/assets/a7cecf1c-2c8c-44fc-8acb-6747bccf9740)
![image](https://github.com/user-attachments/assets/992d3a23-4780-40dd-95d1-ce7bbd17fc9c)
</details>
