### ISSUE TITLE
Spyder continuously spawns 

### ISSUE THREAD

**Issue by pvir** [spyder-ide/spyder#23455]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Sometimes Spyder starts spawning an unlimited amount of processes like this, apparently in a busy loop:
```
bash -l -c python3.12 -c import os; print(dict(os.environ))
```
which almost completely hangs the system.

To resolve the situation, I have to `pkill -9 spyder` and `pkill -9 -f python3.12`, to kill hundreds of spawned bash processes and prevent more from spawning. The python3.12 is that from the same condaforge install as Spyder.

### What steps reproduce the problem?

This is unclear, but it happens sporadically on one specific system:

Spyder from current condaforge, on RHEL 9.4.

When it occurred, I had started Spyder from gnome-shell, not from terminal.

### What is the expected output? What do you see instead?

Spyder not be able to get in a state where it spawns bash processes in a busy loop.

## Versions

* Spyder version: 6.0.3  (conda)
* Python version: 3.12.6 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: Linux-5.14.0-427.42.1.el9_4.x86_64-x86_64-with-glibc2.34

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                  :  3.11.11 (OK)
asyncssh >=2.14.0,<3.0.0         :  2.19.0 (OK)
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.1.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20241021 (OK)
github >=2.3.0                   :  2.5.0 (OK)
importlib_metadata >=4.6.0       :  8.5.0 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.31.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.2 (OK)
jellyfish >=0.7                  :  1.1.3 (OK)
jsonschema >=3.2.0               :  4.23.0 (OK)
keyring >=17.0.0                 :  25.6.0 (OK)
nbconvert >=4.0                  :  7.16.5 (OK)
numpydoc >=0.6.0                 :  1.8.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.4 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  6.1.1 (OK)
pygments >=2.0                   :  2.19.1 (OK)
pylint >=3.1,<4                  :  3.3.3 (OK)
pylint_venv >=3.0.2              :  3.0.4 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0           :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
pyuca >=1.2                      :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.4 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.6.1,<5.7.0         :  5.6.1 (OK)
qtpy >=2.4.0                     :  2.4.2 (OK)
rtree >=0.9.7                    :  1.3.0 (OK)
setuptools >=49.6.0              :  75.6.0 (OK)
sphinx >=0.6.6                   :  8.1.3 (OK)
spyder_kernels >=3.0.2,<3.1.0    :  3.0.2 (OK)
superqt >=0.6.2,<1.0.0           :  0.7.0 (OK)
textdistance >=4.2.0             :  4.6.2 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  6.0.0 (OK)
xdg >=0.26                       :  0.28 (OK)
yarl >=1.9.4                     :  1.18.3 (OK)
zmq >=24.0.0                     :  26.2.0 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  3.10.0 (OK)
numpy >=1.7                      :  2.2.1 (OK)
pandas >=1.1.1                   :  None (NOK)
scipy >=0.17.0                   :  1.14.1 (OK)
sympy >=0.7.3                    :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @pvir, thanks for reporting. You said:

> When it occurred, I had started Spyder from gnome-shell, not from terminal. This has now happened not every time I use Spyder on this setup, but relatively often.

I don't know why this is happening in your system. I also use Linux (Ubuntu 22.04) and I'm no seeing anything like that, so my guess is that it's related to something in your setup (plus, it hasn't been reported by other Linux users).

A workaround for this is to start Spyder from the command line. Let us know if that solves the problem for you.

**Comment by pvir** [comment]
The problem likely is coming from https://github.com/spyder-ide/spyder/blob/34fc0dd3179f850e7dc2d4622944af386656b40e/spyder/utils/environ.py#L106 which calls bash etc. to try to get environment variables of login shell. It's not clear to me what exactly is calling this function repeatedly.

I'm not really looking for workarounds here (I can just edit out that problematic code for this installation), this bug report is mainly for you to be aware of that on some cases this code seems to cause problems.

**Comment by casimir7** [comment]
Thanks to the OP for reporting and thanks to all responders.
Just to confirm: I am having the same issue with the stock-installation of Spyder 6.03 (pip) with IPython 8.26.0 on fedora 41.
Python 3.13.1 64-bit | Qt 5.15.15 | PyQt5 5.15.10 Linux 6.12.10-200.fc41.x86_64 (x86_64) 
The issue appeared with one of the last updates around Jan 1.

When I start Spyder or just (re-)start a kernel inside the spyder console, this results in hundreds of bash instances that seem to multiply themselves.
One can kill them using `killall bash` but one needs to do that fast and repeatedly for ~a minute. Otherwise the system freezes.
After the last bash instance is killed, everything is back to normal.

I tried all steps from the troubleshooting guide apart from installing spyder in a virtual environment. Resetting the configuration or complete fresh install of spyder and the entire python toolchain did not help.
Please indicate if any further info is required.

**Comment by pvir** [comment]
As a workaround, I've made the following edit to the Spyder installation, and the problem seems to have disappeared:
```diff
--- spyder/utils/environ.py	2025-01-28 14:01:10.553385181 +0200
+++ spyder/utils/environ.py	2025-01-14 14:33:18.411784314 +0200
@@ -103,7 +110,10 @@
         env_var = dict(
             [winreg.EnumValue(key, k)[:2] for k in range(num_values)]
         )
-    elif os.name == 'posix':
+    elif os.name == 'posix' and False:
```
Haven't yet managed to find out what exactly is calling this in a loop on this machine.

I've also been using Spyder on current Fedora 41, but on that machine I *do not* see the issue for some reason.

**Comment by casimir7** [comment]
I tried the proposed patch by @pvir and it works on my machine. 
Further, I did a bit of debugging on environ.py.
The bash instances are triggered by this code:

```
stdout, stderr = proc.communicate(
                    timeout=3 if running_in_ci() else 0.5
                )
```

However, I do not understand why.

**Comment by ProodjePindakaas** [comment]
I am experiencing the same issue, but remarkable only when launching spyder outside the terminal.
When it is launched through the terminal it does not spawn all the bash processes.

Versions:
 - spyder: 6.0.5-1.fc42
 - Python: 3.13.3
 - Qt: 5.15.17-1.fc42
 - PyQt5: 5.15.11
 - Fedora 42
 - Kernel 6.14.9-300.fc42.x86_64

**Comment by ccordoba12** [comment]
@ProodjePindakaas, things should have improved in 6.0.7. Please update when it's available in Fedora and let us know what you find.

**Comment by casimir7** [comment]
@ccordoba12 : Sorry for the bad news, the issue is still present in 6.1.0 on FC43.

**Comment by ccordoba12** [comment]
@casimir7, I think we fixed it in 6.1.2. Please try our [Linux installer](https://www.spyder-ide.org/download) and let us know if that's the case.

**Comment by casimir7** [comment]
Ok, I tried. And I remembered why a long time back I swore myself never to use non-distro packages for spyder any more.
In short, the installer from the spyder website installs a new conda environment but somehow fails to link the new environment in Fedora.

What happened:
The installer reports successful installation, although it shows two errors
`Could not find the Qt platform plugin "wayland" in ""
`
and
`fromIccProfile: failed minimal tag size sanity
`
The newly installed link 'Spyder-6' in the start menu of spyder does not start Spyder 6.1.3 but Spyder 5.5.6, which seems to be a remnant of my attempts some time back. I just wonder why the installer did not replace it. The install directory `~/.local/spyder-6` did not exist before today's installation.
On the console, I can activate the environment via conda (starting from the standard directory, the new installation was directed to [~/.local/spyder-6]` as the executables are not found, otherwise). Conda again starts spyder 5.5.6. This spyder 5.5.6 then recognizes that spyder 6.1.3 is available and asks if I want to install that, which I accept. However, nothing happens. On the console, only the error message 
`/bin/sh: line 1: open: command not found` is left.

I did check that the actual executable running when Spyder 5.5.6 is started is the newly installed one. The starting command was:
/home/<username>/.local/spyder-6/envs/spyder-runtime/bin/python3.12 /home/<username>/.local/spyder-6/envs/spyder-runtime/bin/spyder`.
I also checked that (apart from some old metadata) there is no executable for spyder 5.5.6 on my PC before the installation. So I am a bit puzzled. Is the installer version on the website wrong?

If you could advise me on what would be the most reasonable course of action, I will happily follow and test the version!

**Comment by ccordoba12** [comment]
> If you could advise me on what would be the most reasonable course of action, I will happily follow and test the version!

* You can use a Xorg session instead of a Wayland one. Then the installer should work as expected.
* I'm not sure if PyQt from PyPI comes with QtWayland, but you can also create a virtualenv and install Spyder on it with pip.

If both things fail, you can uninstall our installer with `uninstall-spyder` in a new terminal, and then wait until 6.1.3 or higher is released by Fedora (6.1.0 was released six months ago, by the way. That's why we created our own installer: Spyder is either quite outdated or has wrong dependencies in most distros).

**Comment by casimir7** [comment]
@ccordoba12: Thanks for the hints! I installed spyder 6.1.3 using pip in a venv and this works flawlessly without spawning bash processes.
However, I do start this spyder instance from the shell inside the venv. I cannot rule out that the issue still appears if, as @ProodjePindakaas remarked, it is launched via the os launcher menu.

**Comment by ccordoba12** [comment]
> However, I do start this spyder instance from the shell inside the venv. I cannot rule out that the issue still appears if, as @ProodjePindakaas remarked, it is launched via the os launcher menu.

You're right, I forgot about that. The issue only happens when Spyder is started from the launcher menu. To test that, please take our desktop file:

https://github.com/spyder-ide/spyder/blob/master/scripts/spyder.desktop

and replace `spyder` in `TryExec` and `Exec` by the full path to the `spyder` executable in your venv.

**Comment by casimir7** [comment]
@ccordoba12 : The `spyder.desktop` file (with correct exec path) is not accepted as a valid desktop launcher on Fedora. Anyway, I created a new one using the builtin dialog for that, linked it to the spyder executable in the venv, and unfortunately, it creates a flood of bash instances again. Sorry for the bad news. The issue is **NOT fixed** in 6.1.3.

**Comment by ccordoba12** [comment]
@casimir7, ok, but this is not something directly caused by Spyder because it only uses a shell script run interactively to get your environment variables.

So, you need to go through your `~/.bashrc`, `~/.zshrc`, `~/.profile`, `/etc/bash.bashrc`, `/etc/zsh/zshrc` and `/etc/profile` (depending on what shell you use), comment everything, and start uncommenting line by line to see what's causing the problem. Then we'll be able to adjust our script to avoid the problematic piece of code.

**Comment by casimir7** [comment]
I found the time to do some more debugging. The bash instances are indeed triggered by part of my `/etc/bashrc`, which is called from `~/.bashrc`. The relevant section in `/etc/bashrc`is:
```
# Only display echos from profile.d scripts if we are no login shell
    # and interactive - otherwise just process them to set envvars
    for i in /etc/profile.d/*.sh; do
        if [ -r "$i" ]; then
            if [ "$PS1" ]; then
                . "$i"
            else
                . "$i" >/dev/null
            fi
        fi
    done
```
Here, `$PS1` is set earlier to `PS1="[\u@\h \W]\\$ "` (this is just the user greeting). 
As far as I understand, the for loop iterates all the startup scripts in /etc/profile.d. However, if I execute this as a user, most of these are not runnable, as the `x` is missing in the permissions by default, so that they are not executed after startup. The remaining ones I executed manually and they do not spawn bash instances. What remains strange to me is: The `bashrc` should only be executed at startup or login, not just in order to retrieve environment variables. 
Also, I never changed anything in either of these files. They are entirely stock. Therefore, I wonder if, despite the above code seems to trigger this bug, the actual cause may still be the way Spyder searches for environment variables. No other program on my machine triggers this behavior, so the `bashrc` cannot be that wrong, after all. Couldn't you just use a more robust way of getting env vars in Spyder set up?
