### ISSUE TITLE
Run configuration "external terminal" ignored until reboot

### ISSUE THREAD

**Issue by athompson673** [spyder-ide/spyder#23701]
After updating to spyder 6.0.4 from 6.0.3, changing the run configuration for a file to "External Terminal" will not apply until after a reboot. This does not apply to changing back to "IPython Console".

While debugging this, I could not find a way to set the default runner for new files. I can use run configuration per file, but how can I set external terminal the default for all (new) files? Rolling back through versions, it seems like this was lost from spyder 5 to 6?

Also github issue template not working?

Spyder info
* Spyder version: 6.0.4  (pip)
* Python version: 3.12.7 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.11
* Operating System: Windows-10-10.0.19045-SP0

**Comment by athompson673** [comment]
https://github.com/user-attachments/assets/a8a3d0ba-4776-4d22-b7e6-7ebd083fc871

I have not cleared any configs yet, but this should be well separated from my dev environment configs, so I think this was caused simply from a regular update process.

I can seemingly no longer even get it to consistently launch an external terminal even after rebooting spyder.

**Comment by athompson673** [comment]
I've tried taking a longer video of the behavior, but it's always too big for github... 

Here's my process to repeat the bug so far:
 - Delete `.spyder-py3\config\transient.ini` to reset the run configs
 - make a new file with `print("hello world")` and save
 - run it with default IPython console (works as expected)
 - open run config per file (ctrl-f6)
 - select "External Terminal" and hit OK
 - click run button (or f5): still runs in IPython console, and not in an external terminal
 - close spyder, and re-open
 - click run button: file runs first time in external terminal
 - click run button again: file runs in IPython terminal all subsequent times.

**Comment by ccordoba12** [comment]
Ok, thanks for the detailed instructions. According to what you said:

> click run button: file runs first time in external terminal

This is a bug. We should *always* run the file in the IPython console.

> click run button again: file runs in IPython terminal all subsequent times.

That's the change I implemented in 6.0.4, i.e. to always use the IPython console to run Python files regardless of what's selected in `Configuration per file` (as I said before, it was quite confusing to use that dialog to set a runner besides configuring it).

> I can seemingly no longer even get it to consistently launch an external terminal even after rebooting spyder.

Now you need to go to the menu entry `Run > Run in external terminal`. For 6.0.5 we could add a shortcut to that action so it's easier to trigger it.

**Comment by athompson673** [comment]
@ccordoba12 

> This is a bug. We should always run the file in the IPython console.
> ...
> That's the change I implemented in 6.0.4, i.e. to always use the IPython console to run Python files regardless of what's selected in `Configuration per file`

This to me seems like a regression then to the functionality of being able to configure how code gets run. Generally I either have code that gets run in IPython, or it is for some reason incompatible and needs to be run externally (for example developing Qt applications). Basically it is generally only one or the other for me, and it doesn't change much for a given file, so configuring one as the default seems very correct and natural to me.

I understand it was somewhat inconsistent with the neighboring actions (run selection and run cell) always running in IPython, but that was actually quite useful in itself being able to use the more advanced features of IPython for small segments of code where running the entire file would crash unless run externally. I don't know about others, but it never seemed confusing to me that the actions which only partially ran code, or interacted in more advanced ways (ie: profiling/debugging) would ignore the external terminal setting (which did apply to the "run" action).

> For 6.0.5 we could add a shortcut to that action so it's easier to trigger it.

To me that's really bare minimum. I would say a toolbar button would also be required, but really I would prefer a way to achieve the prior behavior. If it is confusing to use the same dialog to configure the runners and to select the default, would it be okay to have a separate dialog to select the "default runner" which is called with F5 or the "run" button? Maybe even dynamically change the icon on the run toolbar button based on the "default runner" (sticking with the ▶ and $ icons given in the menu)?

**Comment by ccordoba12** [comment]
> This to me seems like a regression then to the functionality of being able to configure how code gets run.

I think it's a regression to the way the `Configuration per file` worked in Spyder 5 before. But keeping that behavior was really confusing in this situation (which is more common than yours):

* Open that dialog to configure the debugger (e.g. to use a dedicated console while doing it).
* Close it and click on the `Run` button to run the file (not debug it) and see that a debugging session was started.
* Click on the `Run cell` or "Run selection"  buttons and see that `%debugcell` or `%debug` were called instead.

Since we have dedicated buttons for debugging a file, cell and selection, I think it's wrong to tie the selected runner in `Configuration per file` to the Run equivalent buttons.

> I don't know about others, but it never seemed confusing to me that the actions which only partially ran code, or interacted in more advanced ways (ie: profiling/debugging) would ignore the external terminal setting (which did apply to the "run" action).

That's a matter of expectations. But when I saw the situation I described above I found it really confusing and thought we needed to fix it.

> That would go a long way to making this better.

The best we can do for 6.0.5 is to allow users set a shortcut for the `Run in an external terminal` action and fix the bug you mentioned above.

> A toolbar button would also be useful

I think that's too much to run files in an external terminal, sorry. Most probably the majority of users are not going to use it.

> but really I would prefer a way to achieve the prior behavior. If it is confusing to use the same dialog to configure the runners and to select the default, would it be okay to have a separate dialog to select the "default runner" which is called with F5 or the "run" button? Maybe even dynamically change the icon on the run toolbar button based on the "default runner" (sticking with the ▶ and $ icons given in the menu)?

I think it's better to use a new dialog to select a default runner, as you said. But due to the way the new architecture to run files is designed, that would apply for cells and selections as well (and please don't try to change that. The architecture is complex enough to change it just for this).

However, that wouldn't affect your use case because the external terminal can't run cells and selections, just files.

**Comment by RedAero** [comment]
I'd just like to say that the fundamental issue - that the "Run configuration per file" dialog's "Runner" option is essentially non-functional - is still present a year later in version 6.1.2.

**Comment by ccordoba12** [comment]
@RedAero, that's not going to change (read my [comment](https://github.com/spyder-ide/spyder/issues/23701#issuecomment-2726097252) above and previous ones for the rationale).

A simple way to run files in an external terminal is by setting a shortcut for the `Run in external terminal` action in Preferences:

<img width="920" height="699" alt="Image" src="https://github.com/user-attachments/assets/eab9e987-c26e-4159-ac70-646ee6795b0b" />

A proper solution to this would be to allow users set a specific runner for their files, but that's not so simple.

**Comment by jnsebgosselin** [comment]
I appreciate the changes that you made in Spyder 6. The new action in the `Run` menu and the shortcut to run a file in an external terminal are neat additions.

However, I think it would be very helpful to add a brief explanation in the `Run configuration per file` dialog about its purpose. I also initially thought this was a regression bug, since the workflow has changed from Spyder 5, but the configuration dialog has remained somewhat similar.

For example, you could add something like:

> **Note:** This configuration dialog lets you choose how each file is executed in different runners (such as the IPython console, external terminal, debugger, etc.). It does not allow you to select the runner itself for code execution, as was possible in Spyder 5.  
>  
> In Spyder 6, to use a specific runner, select the desired action from the `Run` menu. For instance, to run your code in an external terminal, use the `Run in external terminal` option in the `Run` menu.

I think this would help clarify the workflow for users migrating from previous versions.

**Comment by ccordoba12** [comment]
Thanks for the suggestion @jnsebgosselin. I like the idea but I think it's too much text to add it to the dialog itself.

However, we could include it in a tooltip, as we do in the Remote connections dialog:

<img width="1027" height="287" alt="Image" src="https://github.com/user-attachments/assets/fed224d0-124d-412c-aa4c-b83720a94f6c" />

Would that be ok?

**Comment by jnsebgosselin** [comment]
@ccordoba12 Yes, this is a good idea.
