### ISSUE TITLE
Help pane is now available in Spyder 6.1.0?

### ISSUE THREAD

**Issue by neurosignal** [spyder-ide/spyder#25293]
The layout of 6.1.0 seems to be changed. Now there is no _View_ menu anymore, but there is _Window_ instead. There are _Window_ -> _Panes_ but no _Help_ option to enable. I tried different ways but was unable to get the _Help_ under _Panes_. Any suggestions?
Thank you.

**Comment by ccordoba12** [comment]
Hey @neurosignal, thanks for reporting. The Help pane should be available unless Spyder is not able to find the QtWebEngine module, in which case it's disabled automatically.

So, my question for you is: how did you install Spyder? I'm asking because if you used our standalone installers or Anaconda, you shouldn't have a problem like this.

**Comment by neurosignal** [comment]
Thank you @ccordoba12 for the prompt response. I installed Spyder using _conda_ earlier. Possibly QtWebEngine was missing, creating this issue; I am not sure because I wiped out that environment and installed a new one. In the new one, I installed Spyder using _pip_ and I can see the _Help_ now. Also I can see that the _PyQtWebEngine_ is installed in the new env.
Thank you.

**Comment by neurosignal** [comment]
Closing as the issue was resolved.

**Comment by ccordoba12** [comment]
Great! Glad you were able to solve this problem.

**Comment by Ticonderoga** [comment]
I think that the way to check PyQtWebEngine is not perfect because on an arch install I lost the help Pane as well. On my PC a simple 

`yay -Q | grep webengine`

gives me 

```
python-pyqt6-webengine 6.10.0-1
qt6-webengine 6.10.0-3
```

and Spyder refuses to show me the help Pane and it was installed with 

`yay -S spyder`

The version is 6.1.0.3
```
yay -Q | grep spyder

python-pyls-spyder 0.4.0-6
python-spyder-kernels 3.1.1-1
spyder 6.1.0-3
```

If you need more info let me know

**Comment by ccordoba12** [comment]
@Ticonderoga, you said:

> I think that the way to check PyQtWebEngine is not perfect because on an arch install I lost the help Pane as well

Unfortunately, Arch is the distro that packages Spyder the worst. According to many bug reports throughout the years, it's always broken or semi-broken there due to their maintainers forcing Spyder to work with package versions it's not prepared for. That contrast significantly with Debian and Fedora, which either collaborate with us to or at least wait until we can add support for new dependencies.

If you'd like to have a smooth experience with Spyder, please use our Linux installer:

https://www.spyder-ide.org/download

If not, please report your problem in the Arch bug tracker.

**Comment by Ticonderoga** [comment]
Thanks for you're fast reply ... for now I will stick to the Arch  way. I found the fix by myself by removing the qt5 stuff

`yay -R python-pyqt5 python-pyqt5-webengine`

and spyder will find my PyQtWebEngine. So I still don't know who to blame ... Anyway I love spyder even if I'm not really a fan of  the conda stuff.
