### ISSUE TITLE
Crash after update IPython to 4.0

### ISSUE THREAD

**Issue by dyngts** [spyder-ide/spyder#2608]
Hi guys,

I'm just updating my ipython 3.2.1 to 4.0. But, problem appears when i tried to opening Spyder using command

```
~/anaconda/bin/spyder
```

And suddenly throwing this following errors:

```python
/home/hadyan/anaconda/lib/python2.7/site-packages/IPython/qt.py:13: ShimWarning: The `IPython.qt` package has been deprecated. You should import from qtconsole instead.
  "You should import from qtconsole instead.", ShimWarning)
Traceback (most recent call last):
  File "/home/hadyan/anaconda/lib/python2.7/site-packages/spyderlib/spyder.py", line 2336, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/hadyan/anaconda/lib/python2.7/site-packages/spyderlib/spyder.py", line 2220, in run_spyder
    main.setup()
  File "/home/hadyan/anaconda/lib/python2.7/site-packages/spyderlib/spyder.py", line 766, in setup
    from spyderlib.plugins.inspector import ObjectInspector
  File "/home/hadyan/anaconda/lib/python2.7/site-packages/spyderlib/plugins/inspector.py", line 41, in <module>
    from spyderlib.widgets.ipython import IPythonControlWidget
  File "/home/hadyan/anaconda/lib/python2.7/site-packages/spyderlib/widgets/ipython.py", line 28, in <module>
    pygments_patch.apply()
  File "/home/hadyan/anaconda/lib/python2.7/site-packages/spyderlib/pygments_patch.py", line 27, in apply
    from IPython.frontend.qt.console.pygments_highlighter import RegexLexer
ImportError: No module named pygments_highlighter
Segmentation fault (core dumped)
```

FYI, i'm completely using anaconda packages with:
- Python 2.7.10
- Spyder 2.3.5.2
- IPython/Jupyer 4.0

Thanks Guys!!!

**Comment by ccordoba12** [comment]
I can't reproduce your error, using a clean virtualenv.

I ran:

    pip install qtconsole
    pip install spyder

and everything is working fine for me.

I imagine you used pip to do the update in Anaconda. Let's wait until there are proper Anaconda packages to see if the error still shows up.

**Comment by dyngts** [comment]
Hi @ccordoba12 ,

Yes, everything update action were did in Anaconda and i were already ran all your commands, but still not working. What do you think about this bug? is this because newer version of IPython not backward compatible with older version, so the Spyder configuration doesn't run well with newer IPython?

Thanks for your response!!

**Comment by ccordoba12** [comment]
Jupyter 4 is compatible with Spyder. I just confirmed it before posting my previous comment. For this to work you need to uninstall IPython from Anaconda, and run the command above:

     pip install qtconsole

not just

    pip install ipython

I think the problem is that you (most probably) only ran the last one.

**Comment by dyngts** [comment]
Hi @ccordoba12 ,

I were already following all your commands:
1. Uninstall IPython
2. Installing Both packages (qtconsole & IPython) in ordering steps and pip said already up-to-date.
3. Then, run Spyder again. But still not working.

Then, i came up with the following solution: **Uninstalling IPython only**. The spyder run very well, but without ipython console. Then, I'm trying to install IPython again and the problem appear again. What do you think @ccordoba12 ?

**Comment by procha79** [comment]
I actually have the exact same problem. I believe the issue has to do with the pygments_patch file in the spyderlib folder but I am not sure and I don't know how to fix it. I am running Python (x,y)

Python 2.7.6
Spyder 2.3.5.2
IPython/Jupyter 4.0

Thanks,

**Comment by ccordoba12** [comment]
@dyngts, packages for Anaconda will be available in a couple of days, so let's wait until then. In general it's not good to mix conda and pip packages.

@procha79, as you can see from the error posted by @dyngts, the problem is `pygments_highlighter` is not part of IPython, not a problem with Spyder. This clearly points to an installation problem in your side. There's no need to fix any imports in `pygments_patch` because that's taking care of by IPython shims.

**Comment by dyngts** [comment]
@ccordoba12 : Okay, let's wait then. Actually i'm using pip inside on Anaconda package, not pip for desktop environment. So that's must not be a problem.

**Comment by Phlya** [comment]
Got the same problem. Spyder was working fine, then I updated the IPython stack (sudo pip install jupyter). Now spyder doesn't start with the same error. I'm not using Anaconda.

**Comment by mhemeryck** [comment]
Same issue on mac; not using Anaconda.

**Comment by NazBen** [comment]
Same issue for me, on both debian and windows and only since I update to ipython 4.0. I'm note using Anaconda. 

Spyder can launch only if ipython is uninstalled, like @dyngts already suggests.

**Comment by ccordoba12** [comment]
@Phlya, @mhemeryck, @NazBen, what is the error you're seeing? The same one reported by @dyngts?

I say it because I can't reproduce this problem. IPython has a compatibility module that should prevent this problem.

Besides, remember that now one thing is IPython and a different one is Jupyter. If just update IPython and don't install Jupyter (or qtconsole) then things are going to fail for sure.

**Comment by NazBen** [comment]
Yes, the exact same one:
``` python
D58174@dsp133254:/local00/home/D58174$ spyder
/home/D58174/.local/lib/python2.7/site-packages/IPython/qt.py:13: ShimWarning: The `IPython.qt` package has been deprecated. You should import from qtconsole instead.
  "You should import from qtconsole instead.", ShimWarning)
Traceback (most recent call last):
  File "/home/D58174/.local/lib/python2.7/site-packages/spyderlib/spyder.py", line 2336, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/D58174/.local/lib/python2.7/site-packages/spyderlib/spyder.py", line 2220, in run_spyder
    main.setup()
  File "/home/D58174/.local/lib/python2.7/site-packages/spyderlib/spyder.py", line 766, in setup
    from spyderlib.plugins.inspector import ObjectInspector
  File "/home/D58174/.local/lib/python2.7/site-packages/spyderlib/plugins/inspector.py", line 41, in <module>
    from spyderlib.widgets.ipython import IPythonControlWidget
  File "/home/D58174/.local/lib/python2.7/site-packages/spyderlib/widgets/ipython.py", line 28, in <module>
    pygments_patch.apply()
  File "/home/D58174/.local/lib/python2.7/site-packages/spyderlib/pygments_patch.py", line 27, in apply
    from IPython.frontend.qt.console.pygments_highlighter import RegexLexer
ImportError: No module named pygments_highlighter
Erreur de segmentation
```
I tried to uninstall and reinstall the packages using pip, but nothing changed.

All the dependencies seem up to date:
``` sh
D58174@dsp133254:/local00/home/D58174$ pip list
...
ipykernel (4.0.3)
ipyparallel (4.0.0)
ipython (4.0.0)
ipython-genutils (0.1.0)
ipywidgets (4.0.2)
...
jupyter (1.0.0)
jupyter-client (4.0.0)
jupyter-console (4.0.0)
jupyter-core (4.0.3)
...
pip (7.1.0)
...
Pygments (2.0.2)
...
qtconsole (4.0.0)
...
spyder (2.3.5.2)
...
```

I got back to IPython 3.0 and everything is working now :)

**Comment by ccordoba12** [comment]
Thanks @NazBen. Could you give the entire output of `pip freeze` so I can recreate a virtualenv that matches yours?

This way I could start to understand what's happening in this case.

**Comment by NazBen** [comment]
Of course:

``` sh
D58174@dsp133254:/local00/home/D58174$ pip freeze
alabaster==0.7.6
api-proxy==0.1.6
appnope==0.1.0
astroid==1.3.8
autopep8==1.2
Babel==2.0
backports.ssl-match-hostname==3.4.0.2
blaze==0.8.2
certifi==2015.4.28
conda===unknown
Cython==0.23
datashape==0.4.6
decorator==4.0.2
docopt==0.6.2
docutils==0.12
easybuild==2.0.0
easybuild-easyblocks==2.0.0
easybuild-easyconfigs==2.0.0
easybuild-framework==2.0.0
enum34==1.0.4
funcsigs==0.4
functools32==3.2.3.post2
fusepy==2.0.2
gdrivefs==0.14.2
gevent==1.0
gipc==0.4.0
gnureadline==6.3.3
google-api-python-client==1.2
graphviz==0.4.3
greenlet==0.4.2
httplib2==0.8
ipykernel==4.0.3
ipyparallel==4.0.0
ipython==4.0.0
ipython-genutils==0.1.0
ipywidgets==4.0.2
Jinja2==2.8
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.0.0
jupyter-console==4.0.0
jupyter-core==4.0.3
llvmlite==0.6.0
logilab-common==1.0.2
MarkupSafe==0.23
matplotlib==1.4.3
mistune==0.7
mock==1.3.0
multipledispatch==0.4.8
nbconvert==4.0.0
nbformat==4.0.0
networkx==1.10
nose==1.3.7
notebook==4.0.1
numba==0.20.0
numpy==1.9.2
numpydoc==0.5
odo==0.3.3
Orange==2.7.8
pandas==0.16.2
pandoc==1.0.0a8
path.py==7.6
patsy==0.3.0
pbr==1.5.0
pep8==1.6.2
pexpect==3.3
pickleshare==0.5
plotly==1.7.6
psutil==3.1.1
ptyprocess==0.5
pycosat==0.6.0
pydot==1.0.2
pydot2==1.0.33
pyglet==1.2.2
Pygments==2.0.2
pylint==1.4.4
pymc==2.3.4
pyparsing==2.0.3
pyplotter==0.0.6
pyreadline==2.0
pyRserve==0.8.1
PySide==1.2.2
python-dateutil==2.4.2
pytz==2015.4
PyYAML==3.11
pyzmq==14.7.0
qtconsole==4.0.0
QtPy==0.1.2
readline==6.2.4.1
requests==2.7.0
rope==0.10.2
rpy2==2.5.6
SALib==0.4
scikit-learn==0.16.0
scipy==0.16.0
sh==1.11
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.9.0
snowballstemmer==1.2.0
Sphinx==1.3.1
sphinx-rtd-theme==0.1.8
spyder==2.3.5.2
SQLAlchemy==1.0.8
statsmodels==0.6.1
sympy==0.7.6
terminado==0.5
testpath==0.2
toolz==0.7.2
tornado==4.2.1
traitlets==4.0.0
UNKNOWN==0.0.0
vsc-base==2.1.3
```

Thank you.

**Comment by stonebig** [comment]
I see babel 2.0, which may be still a problem ?

**Comment by NazBen** [comment]
@stonebig, I downgraded babel to 1.3 considering #2566, but it made no change.

**Comment by stonebig** [comment]
I think I had the issue, because I forgot to include qtconsole at first.
comparing to you:
- I'm Python3.4, which may receive better treatment from Jupyter team now
- I'm still with jupyter_core-4.0.2 (so previous from you, will try the new soon)

**Comment by SylvainCorlay** [comment]
@ccordoba12 this actually show that we cannot just check that IPython is present anymore but that we need to check for qtconsole etc.. The big split makes optional dependency checks a bit more complicated than before.

**Comment by stonebig** [comment]
my current 'Ipython4' list is at least:
````
Babel-1.3-py3-none-any.whl
decorator-4.0.2-py2.py3-none-any.whl
ipykernel-4.0.3-py2.py3-none-any.whl
ipyparallel-4.0.0-py2.py3-none-any.whl
ipython-4.0.0-py2-none-any.whl OR ipython-4.0.0-py3-none-any.whl
ipython_genutils-0.1.0-py2.py3-none-any.whl
ipywidgets-4.0.2-py2.py3-none-any.whl
Jinja2-2.8-py2.py3-none-any.whl
jupyter-1.0.0-py2.py3-none-any.whl
jupyter_client-4.0.0-py2.py3-none-any.whl
jupyter_console-4.0.0-py2.py3-none-any.whl
jupyter_core-4.0.3-py2.py3-none-any.whl
nbconvert-4.0.0-py2.py3-none-any.whl
nbformat-4.0.0-py2.py3-none-any.whl
notebook-4.0.1-py2.py3-none-any.whl
path.py-7.6-py2.py3-none-any.whl
pickleshare-0.5.tar.gz
qtconsole-4.0.0-py2.py3-none-any.whl
traitlets-4.0.0-py2.py3-none-any.whl
````
... a big split they said

**Comment by ccordoba12** [comment]
So @stonebig, are you seeing this issue or not? But please use the `2.3` branch to test and not `master` because `master` shouldn't have this problem.

**Comment by ccordoba12** [comment]
@SylvainCorlay, I understand now we need to depend on the `qtconsole` package. But what I'm trying to figure out here is if we need to do a new stable release to fix this problem.

Since I've been unable to reproduce this issue, I haven't taken any further steps.

**Comment by stonebig** [comment]
Hi @ccordoba12 

Sorry, I'm currently focussed on having a working Python 3.4 / Qt 5.5.0 / Spyder 3.0.0dev / Jupyter 4.0.0 combination
I'll try other combinations when that one will work great.

Reading you, do you mean it's better tested to use Spyder 3.0.0dev than Spyder 2.3.5.2, for Ipython 4 ?

**Comment by ccordoba12** [comment]
@stonebig, the thing is I removed support for old IPython versions in `master` (i.e. versions less than IPython 3.0). That's why master should be safer at this point than 2.3, for this particular case.

**Comment by ccordoba12** [comment]
Well, I can confirm the error (using one of my Ubuntu VMs). I was hiding behind *it works on my machine* ;-)

The fix is simple, but it's not where most of you have guessed. We just need to set PyQt APi to version 2, and the error goes away.

I'll start to prepare **2.3.6** right away. I hope to release it by Monday at most. Thanks for your patience :-)

**Comment by stonebig** [comment]
Hi this monring, filming the spyder start with a smartphone, I saw also the message 

````
`IPython.qt` package has been deprecated. You should import from qtconsole instead.
  "You should import from qtconsole instead."
````

on spyder-3.0.0dev (and PyQt5.5.0)

but it doesn't fail and spyder starts

**Comment by stonebig** [comment]
Unfortunately, it creates a bug:
````
  File "\site-packages\spyderlib\qt\__init__.py", line 12, in <module>
    assert os.environ['QT_API'] in ('pyqt', 'pyside')
AssertionError

D:>echo %QT_API%
pyqt5
````

**Comment by NazBen** [comment]
Same for me @stonebig. With spyder-3.0.0dev installed on my windows, the message appears but spyder launched and works fine.

I'll try with the 3.0. Monday on Linux.

Thanks for the help.

**Comment by ccordoba12** [comment]
@stonebig and @NazBen, that warning comes from IPython compatibility module. It's just a warning, so don't worry about it. We'll remove it on beta2.

Perhaps I wasn't clear enough, but this issue is **not** a bug in `master`, just on the stable branch (i.e. `2.3`). That's why I need to do a new stable release to fix it.

**Comment by stonebig** [comment]
my fault: you were clear but I misinterpreted the github web interface.

**Comment by ccordoba12** [comment]
@SylvainCorlay, I added `qtconsole` as an optional dependency. We're also now checking for its presence to decide if we can show the *IPython Console* plugin or not.

I think this completes the work needed to support Jupyter 4.0+.

**Comment by rbrackney** [comment]
Hello, I'm receiving the same, or similar error on a fresh install of Ubuntu 15.04 with ipython 4.0, and Python 2.7.9 and Spyder. Specifically, it gives me the following error and crashes on start up:
<pre><code>
/home/ryan/.local/lib/python2.7/site-packages/IPython/qt.py:13: ShimWarning: The `IPython.qt` package has been deprecated. You should import from qtconsole instead.
  "You should import from qtconsole instead.", ShimWarning)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 2354, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 2242, in run_spyder
    main.setup()
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 793, in setup
    from spyderlib.plugins.inspector import ObjectInspector
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 41, in <module>
    from spyderlib.widgets.ipython import IPythonControlWidget
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/ipython.py", line 27, in <module>
    pygments_patch.apply()
  File "/usr/lib/python2.7/dist-packages/spyderlib/pygments_patch.py", line 26, in apply
    from IPython.frontend.qt.console.pygments_highlighter import RegexLexer
ImportError: No module named pygments_highlighter
</pre></code>

Is there a fix for this? I'd be happy to send you any information needed.

**Comment by ccordoba12** [comment]
@rbrackney, sorry for the delay. I'm still fixing other bugs before releasing **2.3.6**. In the mean please downgrade to IPython 3.2.1.

**Comment by mhemeryck** [comment]
:+1:

**Comment by viviancamacho** [comment]
having also the same issue with python 4.0.0. How can I downgrade to IPYTHON 3.2.1 to have spyder working?

**Comment by ProfEaston** [comment]
Just wasted a whole bunch of time figuring out how to downgrade to ipython 3.2.1. It is, of course, simple. You install the version number you want as follows:

conda install ipython=3.2.1

This does also remove the later version. And it fixed the spyder problem for me.

**Comment by ccordoba12** [comment]
@ProfEaston, there is necessary to run only a single command to make Spyder work with the latest IPython:

    conda update spyder

That will update IPython and install the new necessary Jupyter components for Spyder.

**Comment by ccordoba12** [comment]
And, of course, it'll also update Spyder to 2.3.6

**Comment by ProfEaston** [comment]
I gather from your comment that the problem with iPython 4.0 is solved?

Using "conda update spyder" did not solve the problem. Nor did "conda update anaconda" followed by "conda update spyder" nor any other of  many variations. However, your recommendation of changing the version of iPython worked like a charm.

**Comment by ccordoba12** [comment]
@ProfEaston, are you working on Windows with Python 3.4?

**Comment by ProfEaston** [comment]
I am working on Windows 7 with Python 2.7.

For me, the problem came up yesterday when I activated an environment that I created some time ago (but had never installed spyder), and then installed spyder. The conda program was used for all of this (not pip or virtualenv), so the command that appeared to get me in trouble was (executed within the environment):

conda install spyder

However, rolling back the iPython version as you suggested in your message to @rbrackney 5 days ago caused everything to work fine. I just had to figure out how to "roll back."

Finally, because your last message led me to believe that the problem was fixed (which it seems to be), I then updated spyder with

conda update spyder

This has brought everything up to date and working (i.e., Spyder 2.3.6, Python 2.7.8 and iPython 4.0.0).

Thanks for your help on this.

**Comment by NazBen** [comment]
Everything works fine now with the last update. Thank you.

**Comment by ribby** [comment]
I ran into the same problem as @ProfEaston , and I can confirm I typed 

conda update spyder 

Spyder still would not start afterwards, although 

conda install ipython=3.2.1

fixed the error.

**Comment by flyingdisc** [comment]
Same problem, I use Python-xy though (not Anaconda). Windows 7, Python 2.7. 
Just update the spyder, 
`pip install --upgrade spyder` 
Problem solved, thanks.

**Comment by applecool** [comment]
Problem persists on Mac OSX 10.11.1 ElCapitan. Spyder crashes showing a pop-up.

**Comment by ccordoba12** [comment]
Sorry to hear that. Nobody in our team is using 10.11 right now so we 
can't do anything about it.

**Comment by applecool** [comment]
No problem @ccordoba12 . I created an issue here https://github.com/spyder-ide/spyder/issues/2799 and the issue has been fixed with the update. I have added that in the comment. You could go ahead and close the issue.

**Comment by prinsherbert** [comment]
sudo pip install --upgrade spyder

also solved this for me on Ubuntu 15.10, with apt-get installs of spyder, python, ipython, etc.

**Comment by tebzito** [comment]
Thanks for that, it worked well

**Comment by fchirono** [comment]
Hi all. I'm having a slightly different problem here; I have spyder 2.2.5 and upgraded to ipython 4.0.1, and now trying to run spyder gives me the following message:

```
fch1g10@fch1g10-DQ77MK:~$ spyder
/usr/local/lib/python2.7/dist-packages/IPython/qt.py:13: ShimWarning: The `IPython.qt` package has been deprecated. You should import from qtconsole instead.
  "You should import from qtconsole instead.", ShimWarning)
/usr/local/lib/python2.7/dist-packages/IPython/frontend.py:21: ShimWarning: The top-level `frontend` package has been deprecated. All its subpackages have been moved to the top `IPython` level.
  "All its subpackages have been moved to the top `IPython` level.", ShimWarning)
Traceback (most recent call last):
  File "/usr/local/bin/spyder", line 3, in <module>
    start_app.main()
  File "/usr/lib/python2.7/dist-packages/spyderlib/start_app.py", line 72, in main
    from spyderlib import spyder
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 106, in <module>
    from spyderlib.plugins.inspector import ObjectInspector
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/inspector.py", line 39, in <module>
    from spyderlib.widgets.ipython import IPythonControlWidget
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/ipython.py", line 15, in <module>
    from IPython.frontend.qt.console.rich_ipython_widget import RichIPythonWidget
ImportError: No module named rich_ipython_widget
```

Following the recommendations here to upgrade spyder, however, gave me the following error:

```
fch1g10@fch1g10-DQ77MK:~$ sudo pip install --upgrade spyder
Downloading/unpacking spyder from https://pypi.python.org/packages/source/s/spyder/spyder-2.3.8.zip#md5=fb890dc956f606c43d560558159f3491
  Downloading spyder-2.3.8.zip (3.0MB): 3.0MB downloaded
  Running setup.py (path:/tmp/pip_build_root/spyder/setup.py) egg_info for package spyder
    
    warning: no files found matching '*.pot' under directory 'spyderlibplugins'
    warning: no files found matching '*.po' under directory 'spyderlibplugins'
    warning: no files found matching '*.svg' under directory 'spyderlibplugins'
    warning: no files found matching '*.png' under directory 'spyderlibplugins'
    warning: no files found matching '*.' under directory 'doc'
    warning: no files found matching '*.bat' under directory 'app_example'
    warning: no files found matching '*.qm' under directory 'app_example'
    warning: no files found matching '*.svg' under directory 'app_example'
    warning: no files found matching '*.png' under directory 'app_example'
    warning: no files found matching 'CHANGELOG'
Installing collected packages: spyder
  Found existing installation: spyder 2.2.5
    Not uninstalling spyder at /usr/lib/python2.7/dist-packages, owned by OS
  Running setup.py install for spyder
    changing mode of build/scripts-2.7/spyder_win_post_install.py from 644 to 755
    changing mode of build/scripts-2.7/spyder from 644 to 755
    Running Sphinx v1.2.2
    loading pickled environment... not yet created
    building [html]: targets for 18 source files that are out of date
    updating environment: 18 added, 0 changed, 0 removed
    
    looking for now-outdated files... none found
    pickling environment... done
    checking consistency... done
    preparing documents... done
    
    
    dumping search index... done
    dumping object inventory... done
    build succeeded.
    
    warning: no files found matching '*.pot' under directory 'spyderlibplugins'
    warning: no files found matching '*.po' under directory 'spyderlibplugins'
    warning: no files found matching '*.svg' under directory 'spyderlibplugins'
    warning: no files found matching '*.png' under directory 'spyderlibplugins'
    warning: no files found matching '*.' under directory 'doc'
    warning: no files found matching '*.bat' under directory 'app_example'
    warning: no files found matching '*.qm' under directory 'app_example'
    warning: no files found matching '*.svg' under directory 'app_example'
    warning: no files found matching '*.png' under directory 'app_example'
    warning: no files found matching 'CHANGELOG'
    changing mode of /usr/local/bin/spyder_win_post_install.py to 755
    changing mode of /usr/local/bin/spyder to 755
Successfully installed spyder
Cleaning up...
```

And when I check it using pip freeze, my spyder version is still 2.2.5. I tried downgraded ipython 3.2.1 and now spyder works, but trying to upgrade it again gives me the same message as above and spyder is still at 2.2.5. Any ideas on that?

**Comment by jonilaserson** [comment]
To downgrade ipython to version 3.2.1, use:
  sudo pip uninstall ipython
  sudo pip install ipython==3.2.1

(bug is still not fixed in my ubuntu 14.04).

**Comment by lgmventura** [comment]
This issue wasn't resolved. I don't even have PtQt installed and Spyder never launched since it was installed.
Using Ubuntu 14.04.

**Comment by nico972** [comment]
I used: 
>> conda update spyder 

and it solved my problem
