### ISSUE TITLE
Spyder will not start after update

### ISSUE THREAD

**Issue by amkellett** [spyder-ide/spyder#5554]
## Spyder broken after non-clean update

 I updated Spyder on my Win7 machine by using:

`pip install --update spyder`

My computer died in the midst of the update (a hardware issue that has been plaguing me for a few weeks). 

Once I got the computer started again, I resumed the update by retyping the same pip install as above, and I saw a few additional changes and then it completed.  However, when I try to start Spyder from the Anaconda command line I get this:

```
Traceback (most recent call last):
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\Scripts\spyder-script.py", line 5, in <module>
    sys.exit(spyder.app.start.main())
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\app\start.py", line 144, in main
    from spyder.app import mainwindow
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 69, in <module>
    import rope.base.project  # analysis:ignore
ValueError: source code string cannot contain null bytes
```
I see that mainwindow.py was also updated today during this process. 

I checked, and rope is installed an up-to-date.

My old version of spyder was a few months old and I was updating to the version that was being prompted today when I first (successfully) started spyder. 

Any ideas?  Thanks,

**Comment by amkellett** [comment]
Given I had a dirty install, I decided to reinstall rope.  I tried to force an update with:

`pip install --upgrade --force-reinstall rope`

and I got this (note the NULL byte issue again)

`Exception:
Traceback (most recent call last):
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\req\req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\req\req_install.py", line 694, in uninstall
    for path in pip.wheel.uninstallation_paths(dist):
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\wheel.py", line 534, in unique
    for item in fn(*args, **kw):
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\pip\wheel.py", line 554, in uninstallation_paths
    for row in r:
_csv.Error: line contains NULL byte`

**Comment by amkellett** [comment]
Tried to force unistall of rope and tried to force update of spyder and all fail in same way when encountering rope.  I get the EXACT same error as in the comment above.

**Comment by ccordoba12** [comment]
> pip install --update spyder

Sorry, but why did you that? We are very clear in our release page:

https://github.com/spyder-ide/spyder/releases/tag/v3.2.4

That command could (and most probably did) break your Anaconda installation. Please remove/reinstall it and also remove the `.spyder3` directory under your `C:\Users\<your user>` directory.

That should fix the problem. If not, please post the error message you're getting after that.

**Comment by amkellett** [comment]
I renamed .spyder-py3 to bad.spyder-py3, then I uninstalled spyder and then used conda to install it.  When I try to start spyder, I still get the error similar to the original error:

`Traceback (most recent call last):
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\app\start.py", line 144, in main
    from spyder.app import mainwindow
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 69, in <module>
    import rope.base.project  # analysis:ignore
ValueError: source code string cannot contain null bytes
` 

Did you mean for me to remove and reinstall Anaconda?  

I naively followed the instructions that I read when I followed the link on the window that popped up telling me a new version of Spyder was available.  I mention it just in case someone else may make my mistake.  Thanks for your guidance to a newish user

**Comment by ccordoba12** [comment]
> Did you mean for me to remove and reinstall Anaconda?

Yep, that's what I meant.

> I naively followed the instructions that I read when I followed the link on the window that popped up telling me a new version of Spyder was available. I mention it just in case someone else may make my mistake. Thanks for your guidance to a newish user

We also mention in that window to not use `pip` if you're using Anaconda, but you probably missed that message. In any case, this problem is very common, you're not the first one to be bitten by it, so don't worry about it and thanks for your interest in Spyder.

We'll try to deactivate `pip` when users are running Anaconda to avoid this in the future.

**Comment by amkellett** [comment]
I was in too much of a hurry when reading the instructions.  I really like Spyder and hope someday I can help and be more than just a user of your great work. Thanks.

**Comment by ccordoba12** [comment]
I'm closing this one because it's an installation issue and not a Spyder bug per se. Please feel free to keep adding comments here if things don't work for you after reinstalling Anaconda.
