### ISSUE TITLE
Segmentation fault (core dumped) when trying to start conda-installed spyder 3.2.8

### ISSUE THREAD

**Issue by MattJEM** [spyder-ide/spyder#6908]
## Problem Description
I have Spyder 3.2.8 installed through conda. Two days ago it worked, today I am getting a segmentation fault:

``$ spyder``
``Segmentation fault (core dumped)``

### What steps will reproduce the problem?
1. Type in "spyder" at the command line.

### What is the expected output? What do you see instead?
I expect Spyder to start. Instead I get ``Segmentation fault (core dumped)``

### Paste Traceback/Error Below (if applicable)
There's no traceback or error, just ``Segmentation fault (core dumped)``

## Package Versions
* Spyder: 3.2.8 (installed with conda)
* Python: 2.7.14
* Qt: 5.6.2
* PyQt: 5.6.0
* Operating System: Ubuntu 16.04 LTS

### Dependencies
I can't start Spyder.

--------

I've gone through the troubleshooting document and have tried the various suggestions within including uninstalling and reinstalling through conda. I haven't tried installing via source, I'm hoping there is something else going on that won't require that.

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. Please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

If it does happen again and you can isolate why, please describe in detail the circumstances in which the error occurred, and post the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Calling for Help section as a comment to this issue, and we'll try to help if we can.

**Comment by lawpdas** [comment]
I have same problem. Just update qt&pyqt 5.6-->5.9

**Comment by MattJEM** [comment]
Unfortunately RStudio runs in 5.6. The problem has not recurred, but just in case I went ahead and created a separate environment with 5.9.

**Comment by ccordoba12** [comment]
This problem will be solved in our 3.3 version. In the meantime, please downgrade to Qt/PyQt 5.6

**Comment by addyblue** [comment]
same problem with me after downloading first time it never launched.

**Comment by CAM-Gerlach** [comment]
@addyblue Try ``conda install pyopengl``

**Comment by deciomoritz** [comment]
@CAM-Gerlach solution worked for me.

**Comment by akriti22** [comment]
@addyblue    I have tried this command "conda install pyopengl"    but nothing happened...
again and again spyder crashed....

**Comment by CAM-Gerlach** [comment]
@akriti22 Make sure you've first activated the environment in which Spyder is installed (if its not the base one), and that you are running the install command in a system console (specifically, the Anaconda Prompt if on Windows).

Other than that, you'll need to be way more specific if we're to be able to help you. What operating system and version? What Spyder version? How did you install it? What versions of ``qt``, ``pyqt``, and ``python`` do you have (you can read these off ``conda list <insert-package-name-here>``)? What do you mean by 

> but nothing happened...

You should have gotten *some* message when you tried to install ``pyopengl``, positive or negative.

Also, please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

**Comment by ccordoba12** [comment]
@Samarth-Tripathi3, this should be solved by doing

    conda install pyopengl

**Comment by Prosimio** [comment]
conda install pyopengl works for me too

**Comment by mostafaGwely** [comment]
conda install pyopengl works for me too

**Comment by rajendraarora16** [comment]
`conda install pyopengl works for me too` worked for me too.

**Comment by youngzn** [comment]
conda install pyopengl worked for me too.

**Comment by CAM-Gerlach** [comment]
Thanks all for your reports and your patience. Just FYI, we are well aware that's the solution and its fixed with Spyder 3.3.0 now, so no need to keep posting it further.

**Comment by Ovesta** [comment]
For me worked  #conda install pyqt
(Use conda install pyqt to get these #Python bindings for the Qt framework.)

**Comment by CAM-Gerlach** [comment]
@Ovesta If you didn't have ``PyQt`` in your environment, that's another issue entirely...it should have been automatically installed along with Spyder if following one of our recommended install methods (particularly Anaconda, as you've apparently used). Glad you've got Spyder working though.

For the record, the fix for the ``pyopengl`` issue discussed here is now released to the broader public with Spyder 3.3.0.

**Comment by kamrankh068** [comment]
conda install pyopengl
it is not work for me in ubuntu 18.04

**Comment by hammad97** [comment]
conda install pyopengl
worked for me. 
Thankss.

**Comment by wtrungvu** [comment]
Thank you!
worked for me
conda install pyopengl

**Comment by Ceasar9** [comment]
it does not work on ubuntu 18.04.1:
`conda install pyopengl`

**Comment by CAM-Gerlach** [comment]
@Ceasar9 You shouldn't need to install ``pyopengl``, as Spyder has included the fixes built in since 3.3.0 (the current version is 3.3.1). You can update with ``conda update spyder``. Also, you could try downgrading Qt with ``conda install pyqt=5.6``, as well as the other fixes suggested in  the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections,

**Comment by SatishTelaprolu** [comment]
it worked for me on Ubuntu 18.04 LTS 
conda install pyopengl

**Comment by CAM-Gerlach** [comment]
@SatishTelaprolu As we've said several times, the real fix is to just update to Spyder >=3.3.0 (the current version is 3.3.1), which resolves the issue as well as patches other bugs and adds a number of enhancements, without the need for this workaround. Thanks.

**Comment by kamrankh068** [comment]
yes it does not work so what i do

**Comment by kamrankh068** [comment]
see this picture and please tell me what i do

**Comment by kamrankh068** [comment]
thanx it work😊

**Comment by aliabavi** [comment]
I have the same issue (segment fault when try running spyder). I don't use conda. Do you have suggestions?

**Comment by CAM-Gerlach** [comment]
@aliabavi We recommend you use Anaconda, since ``pip`` is for expert users only who are able to solve the resulting install problems on their own. In any case, if its the same issue, updating Spyder should fix it. Other than that, please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

**Comment by jupiterjosh** [comment]
Fyi same issue as of 2018-01-10 -- installing pyopengl fixed it.  

Fresh install of Linux Mint 19.  
Fresh install of Anaconda 4.5.11.  (all default parms/locations; did not sudo install)
Run spyder, seg fault.

**Comment by CAM-Gerlach** [comment]
@jupiterjosh As we've mentioned before in the thread, this was fixed many months ago in Spyder 3.3.0, and so to fix it you should simply update Spyder (e.g. ``conda update spyder``). I added a prominent note to the top of the OP to try to make sure no more people keep missing it, since its a fairly long thread (which certainly isn't helped by people continuing to post about ``conda install pyopengl``).

> Fresh install of Anaconda 4.5.11. (all default parms/locations; did not sudo install)

FYI, this must be substantially older than the current, which would naturally contain a quite old version of Spyder; the most recent version of Anaconda is 5.2.0 released several months ago by now.

**Comment by jupiterjosh** [comment]
@CAM-Gerlach Thanks for the info.  For someone reading this thread in Sept 2018, it's a little more confusing than what it may be to someone who has followed the thread since the OP.  It looked to me when I was reading the comments that it was thought to be fixed in 3.3.0 but people were still having problems which is why I reported the issue.  Since I had a fresh install of Anaconda that was packaged on 9/27 (I misreported the version -- I was running 5.3 -- 4.5.11 was my conda version), I thought I was running the latest version of Spyder.  It appears Continuum is still packaging Spyder 3.2.8 as of Anaconda 5.3.

**Comment by CAM-Gerlach** [comment]
> conda update spyder only updates Spyder to version 3.2.8 as of Anaconda version 5.3 for Python 3.7

Okay, thanks for the additional information @jupiterjosh . Something weird's going on with your install, as this certainly shouldn't be the case. On Windows (8.1 x64), I created a fresh Python 3.7 environment and ran ``conda install spyder``, and got 3.3.1 (as I have several times before); I also tried a full anaconda install (``conda install anaconda``) and that gave me Spyder 3.3.1 as well; as this is the same Anaconda and Python version and the build number is zero, it must be the same build you downloaded. Therefore, if you installed 5.3.0 fresh, Spyder 3.3.1 should have been installed be default; if you did ``conda update spyder`` or ``conda update anaconda`` from a 5.2.0 install, I'm not sure why it wouldn't have updated Spyder to 3.3.1 since it is hard-pinned to that version and the install would fail otherwise, unless there is a bug, inconsistency or pinning issue on your particular platform.

Are you *sure* you have Spyder 3.2.8 still in the environment you're trying to update? Are you sure you're running Spyder from that environment? What OS and bitness are you on? What were the exact commands/steps you used to update ``anaconda`` and ``spyder``?  Can you try creating a fresh environment just for Spyder (``conda create -n your-env-name-here python=3.7``, ``activate`` it then ``conda install spyder``)?

**Comment by ccordoba12** [comment]
@CAM-Gerlach, I think @jupiterjosh means that the default Spyder version that comes with Anaconda 5.3 is 3.2.8, not 3.3.1.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 , I don't think that's the case. since @jupiterjosh explicitly ran ``conda update spyder`` as stated above, and furthermore Anaconda 5.3 comes with 3.3.1 (as confirmed by both downloading the ``requires`` file in the tar package, and by test installing ``anaconda`` 5.3.0 in a fresh environment. That's why I'm not sure what's preventing Spyder from being updated to 3.3.1, unless there's something user-specific going on.

**Comment by CAM-Gerlach** [comment]
@jupiterjosh Perhaps Spyder is being pinned to the version specified in the ``anaconda`` metapackage. If so, you could uninstall it with ``conda uninstall anaconda`` (which would basically just remove the pinning), or you could create a fresh environment just for Spyder with the commands specified at the end of my first post to you above, and use spyder from there (launching via Anaconda Navigator or the command line ``spyder`` rather than the shortcut to make sure it launches from the correct environment).

**Comment by JoaoGF21** [comment]
> For me worked #conda install pyqt
> (Use conda install pyqt to get these #Python bindings for the Qt framework.)

It worked for my too.
Spyder was working in the base of conda, but it was not working in the environment.

**Comment by Paritosh535** [comment]
conda install pyopengl
it is working :)

**Comment by CAM-Gerlach** [comment]
> conda install pyopengl

@Paritosh535 As we've stated numerous times in this thread and in large, bold type at the top of this thread, you should no longer need to install ``pyopengl``, and instead the proper solution is to simply update Spyder, e.g. with ``conda update spyder``. I've edited the one developer comment from several months ago that stated the fix as ``conda install pyopengl`` to reflect this current situation; otherwise I'm not sure how people are still getting the out of date solution. Thanks.

**Comment by resperic** [comment]
So many times above it's been stated "simply update Spyder 3.3.0", but I'm getting the segmentation fault error with Spyder 3.3.2.

**Comment by CAM-Gerlach** [comment]
@resperic Then its likely a different issue, then. Try (in order; assuming you're using conda as we recommend):

1. ``conda update pyqt qt qtpy``
2. ``conda install pyopengl``
3. ``spyder --opengl=OPENGL_IMPLELENTATION`` with each of ``software``, ``desktop`` and ``gles``
4. ``conda install pyqt=5.6``
5. Do a clean uninstall/reinstall of Anaconda/Miniconda

**Comment by resperic** [comment]
I tried what CAM-Gerlach suggested.

1. & 2.  both resulted in "All requested packages already installed".

3.  spyder  --opengl=software  
This one resulted in "Segmentation fault",  interestingly.

**Comment by CAM-Gerlach** [comment]
Did you try ``spyder --opengl=desktop`` and ``spyder --opengl=gles``? If neither of those do it, there is a good chance ``conda install pyqt=5.6`` will fix it. Failing that, creating a clean environment for Spyder is almost as good as reinstalling, but far faster.

> Perhaps I should jump to 6., uninstall/reinstall...

I ordered the steps that way for a reason, putting those with the highest probability of fixing the problem relative to their time taken and impact on your environment first; therefore, you should complete them in order. Furthermore, reinstalling might not fix it, while one of the other ones might. You should rule out all of them before reinstalling.

**Comment by resperic** [comment]
Thanks CAM-Gerlach, for helping!   

OK I got "Segmentation fault" for `spyder --opengl=desktop` and `spyder --opengl=gles` both.  When I tried `conda install pyqt=5.6`,  "All requested packages already installed".

#5 worked - I was able to fun Spyder; however, there are lots of things I need to `conda install`. The question is, will it still run after I load the entire environment?   

We'll see...

**Comment by CAM-Gerlach** [comment]
> When I tried conda install pyqt=5.6, "All requested packages already installed".

@resperic Oh, I assumed you had 5.9 since I had you run ``conda update pyqt qt qtpy``, correct? Go back to your previous environment (not the new one you created) and try ``conda install pyqt=5.9``. Most likely, your new environment using that version is the reason why its working.

Its possible you may have been mixing packages from ``conda-forge`` and ``defaults``, which is not supported and can cause segfaults like that. If the above still doesn't work, please post the output of ``conda list`` in your previous/main environment (not the new one) inside a ``<details>`` block, like this:

```
<details>
YOUR CONDA LIST OUTPUT
</details>
```

**Comment by resperic** [comment]
When I ran `conda instrall pyqt=5.9` the resulting error message seemed relevant to my problem:

`Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - defaults/linux-64::qt==5.6.3=h8bf5577_3
  - pyqt=5.9 -> qt[version='5.9.*,>=5.9.6,<5.10.0a0']
Use "conda info <package>" to see the dependencies for each package.`

**Comment by CAM-Gerlach** [comment]
It looks like something is pinning your Qt version to 5.6.x. In your freshly created Spyder environment, try running ``conda list qt`` and pasting the results here. Also, in your old environment, try ``conda install -c defaults pyqt=5.9 qt=5.9`` and report the results. Finally, make sure to paste your ``conda list`` output of your old environment in a ``<details>`` block as described above. 

If things work fine in your new environment, you can just install the basics there (``numpy``, ``pandas``, ``matplotlib``, and ``scipy``, as well as ``cython`` and ``sympy`` if you use either), and then set your Python interpreter under ``Preferences > Python interpreter > Use the following Python interpreter`` in your working copy of Spyder to the ``python.exe`` of your previous work environment with all your packages, e.g. under ``Anaconda3/envs/base/python.exe`` (replace ``base`` with whatever your environment is  named). Then, new Consoles will open in that environment, and you will be able to use it just as if you'd launched Spyder from there.

You can change it at any time and have Consoles open from multiple environments simultaniously and tab between them at will, and you can do the same thing to work in other Python installations, virtualenvs/venvs, conda environments, system Python, other Python installs and more, so long as they have the ``spyder-kernels`` package installed so Spyder can talk to them.

**Comment by kalkidanRas** [comment]
"conda install pyopengl " worked for me too on Ubuntu 18.04 LTS.

**Comment by CAM-Gerlach** [comment]
@kalkidanRas Did you read my comment in large bold type at the very top of the first post in this thread?

**Comment by buzonjl** [comment]
pyqt work for me too

**Comment by faraday702** [comment]
Update pyqt.
Happened to me with spyder 4 update as well.

**Comment by mahdipoori** [comment]
conda install pyqt=5.6
It is work for me
thanks
